#!/bin/sh
# suite: V-DPRC-1
# class: object-lifecycle-only
# generated by dpaa2-verify from models/traces/vdprc1.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-DPRC-1.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
# Exit status is recorded as auxiliary evidence only; conformance is
# judged on read-back (DPNI-I6, DPMAC-I8).
run() { n="$1"; shift; echo "+ $*"; "$@"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@")"; echo $? >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpni_0:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpni_0}" --plugged=0 2>/dev/null || true
  [ -n "${OBJ_dpni_0:-}" ] && restool dpni destroy "${OBJ_dpni_0}" 2>/dev/null || true
  [ -n "${OBJ_dprc_3:-}" ] && restool dprc destroy "${OBJ_dprc_3}" 2>/dev/null || true
  [ -n "${OBJ_dprc_2:-}" ] && restool dprc destroy "${OBJ_dprc_2}" 2>/dev/null || true
}
trap teardown EXIT

# step 0: CreateContainer { parent: ObjRef { fam: Dprc, num: 1 } }
OBJ_dprc_2="$(run_create 0 restool --script dprc create dprc.1)"
echo "dprc_2 ${OBJ_dprc_2}" >> "$RESULTS/created.txt"
# expect: dprc_2 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateContainer { parent: ObjRef { fam: Dprc, num: 1 } }
OBJ_dprc_3="$(run_create 1 restool --script dprc create dprc.1)"
echo "dprc_3 ${OBJ_dprc_3}" >> "$RESULTS/created.txt"
# expect: dprc_3 present=true plugged=false
probe 1 0 restool dprc show dprc.1

# step 2: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpni_0="$(run_create 2 restool --script dpni create --container=${OBJ_dprc_2})"
echo "dpni_0 ${OBJ_dpni_0}" >> "$RESULTS/created.txt"
# expect: dpni_0 present=true plugged=false
probe 2 0 restool dprc show ${OBJ_dprc_2}

# step 3: AssignChild { obj: ObjRef { fam: Dpni, num: 0 }, dst: ObjRef { fam: Dprc, num: 3 } }
run 3 restool dprc assign ${OBJ_dprc_2} --object=${OBJ_dpni_0} --child=${OBJ_dprc_3}
# expect: dpni_0 present=true plugged=false
probe 3 0 restool dprc show ${OBJ_dprc_3}

# step 4: Plug { obj: ObjRef { fam: Dpni, num: 0 } }
run 4 restool dprc assign ${OBJ_dprc_3} --object=${OBJ_dpni_0} --plugged=1
# expect: dpni_0 present=true plugged=true
probe 4 0 restool dprc show ${OBJ_dprc_3}

# step 5: Destroy { obj: ObjRef { fam: Dprc, num: 2 } }
run 5 restool dprc destroy ${OBJ_dprc_2}
# expect: dprc_2 present=false
probe 5 0 restool dprc show dprc.1

# step 6: Unplug { obj: ObjRef { fam: Dpni, num: 0 } }
run 6 restool dprc assign ${OBJ_dprc_3} --object=${OBJ_dpni_0} --plugged=0
# expect: dpni_0 present=true plugged=false
probe 6 0 restool dprc show ${OBJ_dprc_3}

# step 7: Destroy { obj: ObjRef { fam: Dpni, num: 0 } }
run 7 restool dpni destroy ${OBJ_dpni_0}
# expect: dpni_0 present=false
probe 7 0 restool dprc show ${OBJ_dprc_3}

# step 8: Destroy { obj: ObjRef { fam: Dprc, num: 3 } }
run 8 restool dprc destroy ${OBJ_dprc_3}
# expect: dprc_3 present=false
probe 8 0 restool dprc show dprc.1

echo "suite V-DPRC-1 complete"
