#!/bin/sh
# suite: V-LIFE-DPNI-1
# class: object-lifecycle-only
# generated by dpaa2-verify from models/traces/vlife_dpni1.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-LIFE-DPNI-1.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
# Exit status is recorded as auxiliary evidence only; conformance is
# judged on read-back (DPNI-I6, DPMAC-I8).
run() { n="$1"; shift; echo "+ $*"; "$@"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@")"; echo $? >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpni_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpni_0}" --plugged=0 2>/dev/null || true
  [ -n "${OBJ_dpni_0:-}" ] && restool dpni destroy "${OBJ_dpni_0}" 2>/dev/null || true
  [ -n "${OBJ_dpcon_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpcon_0}" --plugged=0 2>/dev/null || true
  [ -n "${OBJ_dpcon_0:-}" ] && restool dpcon destroy "${OBJ_dpcon_0}" 2>/dev/null || true
  [ -n "${OBJ_dpbp_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpbp_0}" --plugged=0 2>/dev/null || true
  [ -n "${OBJ_dpbp_0:-}" ] && restool dpbp destroy "${OBJ_dpbp_0}" 2>/dev/null || true
  [ -n "${OBJ_dpmcp_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpmcp_0}" --plugged=0 2>/dev/null || true
  [ -n "${OBJ_dpmcp_0:-}" ] && restool dpmcp destroy "${OBJ_dpmcp_0}" 2>/dev/null || true
}
trap teardown EXIT

# step 0: CreateObject { fam: Dpmcp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpmcp_0="$(run_create 0 restool --script dpmcp create --container=dprc.1)"
echo "dpmcp_0 ${OBJ_dpmcp_0}" >> "$RESULTS/created.txt"
# expect: dpmcp_0 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateObject { fam: Dpbp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpbp_0="$(run_create 1 restool --script dpbp create --container=dprc.1)"
echo "dpbp_0 ${OBJ_dpbp_0}" >> "$RESULTS/created.txt"
# expect: dpbp_0 present=true plugged=false
probe 1 0 restool dprc show dprc.1

# step 2: CreateObject { fam: Dpcon, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpcon_0="$(run_create 2 restool --script dpcon create --num-priorities=2 --container=dprc.1)"
echo "dpcon_0 ${OBJ_dpcon_0}" >> "$RESULTS/created.txt"
# expect: dpcon_0 present=true plugged=false
probe 2 0 restool dprc show dprc.1

# step 3: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_0="$(run_create 3 restool --script dpni create --container=dprc.1)"
echo "dpni_0 ${OBJ_dpni_0}" >> "$RESULTS/created.txt"
# expect: dpni_0 present=true plugged=false
probe 3 0 restool dprc show dprc.1

# step 4: Plug { obj: ObjRef { fam: Dpmcp, num: 0 } }
run 4 restool dprc assign dprc.1 --object=${OBJ_dpmcp_0} --plugged=1
# expect: dpmcp_0 present=true plugged=true
probe 4 0 restool dprc show dprc.1

# step 5: Plug { obj: ObjRef { fam: Dpbp, num: 0 } }
run 5 restool dprc assign dprc.1 --object=${OBJ_dpbp_0} --plugged=1
# expect: dpbp_0 present=true plugged=true
probe 5 0 restool dprc show dprc.1

# step 6: Plug { obj: ObjRef { fam: Dpcon, num: 0 } }
run 6 restool dprc assign dprc.1 --object=${OBJ_dpcon_0} --plugged=1
# expect: dpcon_0 present=true plugged=true
probe 6 0 restool dprc show dprc.1

# step 7: Plug { obj: ObjRef { fam: Dpni, num: 0 } }
run 7 restool dprc assign dprc.1 --object=${OBJ_dpni_0} --plugged=1
# expect: dpni_0 present=true plugged=true
probe 7 0 restool dprc show dprc.1

# step 8: Rescan { container: ObjRef { fam: Dprc, num: 1 } }
run 8 restool dprc sync

# step 9: KernelBind { obj: ObjRef { fam: Dpni, num: 0 } }
# awaited: the kernel probes plugged bus-visible objects on its own; observe the driver link
sleep 1
# expect: dpni_0 driver_bound=true
probe_link 9 0 /sys/bus/fsl-mc/devices/${OBJ_dpni_0}/driver

echo "suite V-LIFE-DPNI-1 complete"
