#!/bin/sh
# suite: V-RECOVERY-1
# class: object-lifecycle-only
# generated by dpaa2-verify from models/traces/recovery.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-RECOVERY-1.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
# Exit status is recorded as auxiliary evidence only; conformance is
# judged on read-back (DPNI-I6, DPMAC-I8).
run() { n="$1"; shift; echo "+ $*"; "$@"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@")"; echo $? >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- pre-state capture (recovery check runs first) ---
# Take this suite from a fresh boot with no MC-mutating services
# started: the pre-state is the recovery-diff reference, so it must
# itself be the boot state.
restool dprc list                > "$RESULTS/pre-dprc-list.txt"
restool dprc show dprc.1         > "$RESULTS/pre-dprc1-show.txt"
restool dprc generate-dpl dprc.1 > "$RESULTS/pre-dpl.dts"

# step 0: CreateContainer { parent: ObjRef { fam: Dprc, num: 1 } }
OBJ_dprc_2="$(run_create 0 restool --script dprc create dprc.1)"
echo "dprc_2 ${OBJ_dprc_2}" >> "$RESULTS/created.txt"
# expect: dprc_2 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateObject { fam: Dpbp, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpbp_0="$(run_create 1 restool --script dpbp create --container=${OBJ_dprc_2})"
echo "dpbp_0 ${OBJ_dpbp_0}" >> "$RESULTS/created.txt"
# expect: dpbp_0 present=true plugged=false
probe 1 0 restool dprc show ${OBJ_dprc_2}

# step 2: Plug { obj: ObjRef { fam: Dpbp, num: 0 } }
run 2 restool dprc assign ${OBJ_dprc_2} --object=${OBJ_dpbp_0} --plugged=1
# expect: dpbp_0 present=true plugged=true
probe 2 0 restool dprc show ${OBJ_dprc_2}

# --- no teardown: the reboot is the teardown (ADR-0003 §7) ---
# The scratch set above is deliberately left in place. Now:
#   1. reboot the board
#   2. run V-RECOVERY-1-postboot.sh with the same results directory
echo "suite V-RECOVERY-1 mutations complete - scratch set left in place; reboot now"
