//! Runtime generation of `systemd.link` files for stable naming (design D3, D4).
//!
//! The reconciler owns naming: it derives `10-dpaa2-<name>.link` files from the
//! topology and writes them into `/run/systemd/network/` (volatile, regenerated each
//! boot) so they cannot drift from `topology.toml`. Each file matches a port's known
//! MAC and sets its stable name; it sorts before the stock `99-default.link` and,
//! from `/run`, outranks `/usr/lib`. This is presentation only — never a
//! reconciliation trigger. Fixed-link ports (no netdev) get no file (task 6.4).

use std::path::{Path, PathBuf};
use std::process::Command;

use dpaa2_api::{
    DesiredPort, DesiredTopology, Error, LinkType, MacAddr, ObservedTopology, Presence,
};

/// The default volatile directory `systemd-udevd` reads link config from.
pub const RUNTIME_NETWORK_DIR: &str = "/run/systemd/network";

/// Renders the contents of a single `.link` file matching `mac` to `name`.
#[must_use]
pub fn render_link(mac: MacAddr, name: &str) -> String {
    format!(
        "# Generated by dpaa2ctl from topology.toml — do not edit.\n\
         [Match]\n\
         MACAddress={mac}\n\
         \n\
         [Link]\n\
         Name={name}\n"
    )
}

/// The link file path for a port name within `dir`.
#[must_use]
pub fn link_path(dir: &Path, name: &str) -> PathBuf {
    dir.join(format!("10-dpaa2-{name}.link"))
}

/// Chooses the MAC to match a port on, in order of trust: the declared MAC, then
/// the connected DPNI's primary MAC, then the DPMAC's burned-in MAC. On the LX2160A
/// the matchable MAC lives on the **DPNI** (inherited from the DPMAC at connect) —
/// `restool dpmac info` does not report it — so the DPNI is the load-bearing source
/// once a port is provisioned. Returns `None` if no candidate is known or the only
/// one is the all-zero placeholder (E6).
#[must_use]
fn match_mac(
    declared: Option<MacAddr>,
    dpni_mac: Option<MacAddr>,
    dpmac_mac: Option<MacAddr>,
) -> Option<MacAddr> {
    declared.or(dpni_mac).or(dpmac_mac).filter(|m| !m.is_zero())
}

/// Generates `.link` files for every present PHY port into `dir`, returning the
/// paths written. Fixed-link ports are skipped (no rename stage).
///
/// # Errors
/// Returns [`Error::Io`] if the directory cannot be created or a file written.
pub fn generate(
    desired: &DesiredTopology,
    observed: &ObservedTopology,
    dir: &Path,
) -> Result<Vec<PathBuf>, Error> {
    std::fs::create_dir_all(dir)?;
    let mut written = Vec::new();

    for port in desired.ports() {
        if port.presence != Presence::Present {
            continue;
        }
        let dpmac = observed.dpmac(port.dpmac);
        // Fixed-link ports never produce a netdev, so they need no rename (6.4).
        if dpmac.map(|m| m.link_type) == Some(LinkType::Fixed) {
            tracing::debug!(port = %port.dpmac, "fixed-link port: no .link generated");
            continue;
        }
        let dpni = observed.dpni_connected_to(port.dpmac);
        let Some(mac) = match_mac(
            port.mac,
            dpni.and_then(|d| d.mac),
            dpmac.and_then(|m| m.mac),
        ) else {
            tracing::warn!(port = %port.dpmac, "no known MAC; cannot generate .link");
            continue;
        };
        let path = link_path(dir, &port.name);
        std::fs::write(&path, render_link(mac, &port.name))?;
        tracing::info!(path = %path.display(), %mac, name = %port.name, "wrote link file");
        written.push(path);
    }

    Ok(written)
}

/// Writes the `.link` files and makes stable names take effect *this boot*.
///
/// Generation must run **after** convergence: the matchable MAC lives on the DPNI,
/// which does not exist until provisioning has created and plugged it. By then the
/// kernel has already named the netdev (`eth1`), so a freshly-written `.link` would
/// only be honoured on the *next* netdev-add event. This re-triggers udev on each
/// misnamed interface so the rename lands now. The interface must be admin-down for
/// the kernel to rename it, which holds during early boot (before `network-pre`).
///
/// # Errors
/// Returns [`Error::Io`] if a file cannot be written, or [`Error::Backend`] if
/// `udevadm` cannot be spawned.
pub fn apply(
    desired: &DesiredTopology,
    observed: &ObservedTopology,
    dir: &Path,
) -> Result<Vec<PathBuf>, Error> {
    let written = generate(desired, observed, dir)?;
    if written.is_empty() {
        return Ok(written);
    }
    reload_udev()?;
    for port in desired.ports() {
        if let Some(current) = rename_target(port, observed) {
            trigger_rename(current, &port.name)?;
        }
    }
    Ok(written)
}

/// The current kernel netdev name of a present PHY port that is still misnamed, if
/// any. Returns `None` when the port is absent/fixed-link, has no netdev yet, or is
/// already named correctly.
#[must_use]
fn rename_target<'a>(port: &DesiredPort, observed: &'a ObservedTopology) -> Option<&'a str> {
    if port.presence != Presence::Present {
        return None;
    }
    if observed.dpmac(port.dpmac).map(|m| m.link_type) == Some(LinkType::Fixed) {
        return None;
    }
    let current = observed.dpni_connected_to(port.dpmac)?.netdev.as_deref()?;
    (current != port.name).then_some(current)
}

/// Re-emits an `add` uevent for `netdev` so udevd re-runs `net_setup_link` and applies
/// the matching `.link` `Name=`, renaming it to `target`. Best-effort and idempotent.
///
/// # Errors
/// Returns [`Error::Backend`] if `udevadm` cannot be spawned.
fn trigger_rename(netdev: &str, target: &str) -> Result<(), Error> {
    let dev = format!("/sys/class/net/{netdev}");
    tracing::info!(from = %netdev, to = %target, "applying stable name via udev");
    let status = Command::new("udevadm")
        .args(["trigger", "--action=add", "--settle", &dev])
        .status()
        .map_err(|e| Error::Backend(format!("failed to spawn udevadm: {e}")))?;
    if !status.success() {
        tracing::warn!(from = %netdev, to = %target, %status, "udevadm trigger did not succeed");
    }
    Ok(())
}

/// Reloads udev link configuration so freshly-written `.link` files are honoured
/// before the netdev-add event fires (system-integration spec). Best-effort.
///
/// # Errors
/// Returns [`Error::Backend`] if `udevadm` cannot be spawned.
pub fn reload_udev() -> Result<(), Error> {
    let status = Command::new("udevadm")
        .args(["control", "--reload"])
        .status()
        .map_err(|e| Error::Backend(format!("failed to spawn udevadm: {e}")))?;
    if !status.success() {
        return Err(Error::Backend(format!(
            "udevadm control --reload: {status}"
        )));
    }
    Ok(())
}
