#!/bin/sh
# suite: V-FIT-1
# class: object-lifecycle-only
# generated by dpaa2-verify from models/board/V-FIT-1/probes.json — do not edit; regenerate instead.
# Read-only fit check (design D12; ADR-0003 §2): every command below only
# reads the board — the container census, the pool ceilings, a DPL
# reconstruction, dpmac info on the lifecycle-safe ports, and the shipped
# dpaa2ctl dry-run/status on the reference intent. NOTHING is created,
# moved, destroyed or labelled, so there is NO teardown trap: this sitting
# is idempotent and safe to re-run as-is. Results are captured under the
# results directory for offline diffing and dispositioning:
#   dpaa2-verify diff --plan V-FIT-1.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- kernel-log window ---
# A marker stamps the sitting's start in the kernel log; the footer saves
# everything after it to dmesg.txt (no teardown runs — nothing is created).
KMSG="dpaa2-verify V-FIT-1 pid $$"
echo "$KMSG start" > /dev/kmsg 2>/dev/null || true
save_dmesg() {
  dmesg 2>/dev/null | awk -v m="$KMSG start" 'w || index($0, m) { w = 1 } w' > "$RESULTS/dmesg.txt"
  [ -s "$RESULTS/dmesg.txt" ] || dmesg > "$RESULTS/dmesg.txt" 2>&1 || true
}

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- read-only helpers ---
# Each step runs one command, captures its stdout/stderr/exit under the
# results directory, and prints one PASS/FAIL line. Exit is judged in
# place for the operator; the captured output is what 4.2 diffs offline.
# run N cmd...: echo, execute, capture stdout, stderr and the exit code.
run() { n="$1"; shift; echo "+ $*"; "$@" >"$RESULTS/step-$n-out.txt" 2>"$RESULTS/step-$n-err.txt"; echo $? > "$RESULTS/step-$n-exit.txt"; }
# expect_zero N label: PASS iff the step exited zero.
expect_zero() { rc=$(cat "$RESULTS/step-$1-exit.txt"); if [ "$rc" = 0 ]; then echo "PASS step $1: $2"; else echo "FAIL step $1: $2 (exit $rc)" >&2; fi; }
# expect_nonzero N label: PASS iff the step was refused (nonzero exit).
expect_nonzero() { rc=$(cat "$RESULTS/step-$1-exit.txt"); if [ "$rc" != 0 ]; then echo "PASS step $1: $2 (exit $rc)"; else echo "FAIL step $1: $2 (exit 0)" >&2; fi; }
# expect_any N label: informational — the exit is evidence, never a verdict.
expect_any() { rc=$(cat "$RESULTS/step-$1-exit.txt"); echo "PASS step $1: $2 (exit $rc — informational)"; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# step 0: container census
# expect: zero exit; the list of DPRC containers on the board (ADR-0003 §5 queries are object-lifecycle-only). Captured whole for 4.2 to diff the live census against the compiled plan (design D12)
run 0 restool dprc list
expect_zero 0 "container census"

# step 1: root container listing with the ownership label column
# expect: zero exit; every object in the root container with its label column. The label is the ownership signal (ADR-0010 §4): an object at an expected name without this control plane's label is somebody else's, and an unlabelled object is DPL-born
run 1 restool dprc show dprc.1
expect_zero 1 "root container listing with the ownership label column"

# step 2: pool ceilings on the MC's own container
# expect: zero exit; the pooled-resource ceilings by type. Only dprc show (and its --resources variant) is legal against mc.global; this is the ceiling half of the fit check the compiled plan's feasibility sums are diffed against (design D12)
run 2 restool dprc show mc.global --resources
expect_zero 2 "pool ceilings on the MC's own container"

# step 3: read-only DPL reconstruction
# expect: zero exit; a DPL device tree reconstructed from live MC state — a read-only query walk that mutates nothing (the reference-capture script uses the same verb read-only). Lets 4.2 separate DPL-injected objects from runtime-added ones and cross-check the unlabelled = DPL-born signal (ADR-0010 §4)
run 3 restool dprc generate-dpl dprc.1
expect_zero 3 "read-only DPL reconstruction"

# step 4: dpmac.4 info
# expect: zero exit; the dpmac attributes. dpmac.4 is a lifecycle-safe unwired port (ADR-0003 §4 port matrix), read only
run 4 restool dpmac info dpmac.4
expect_zero 4 "dpmac.4 info"

# step 5: dpmac.5 info
# expect: zero exit; the dpmac attributes. dpmac.5 is a lifecycle-safe unwired port (ADR-0003 §4 port matrix), read only
run 5 restool dpmac info dpmac.5
expect_zero 5 "dpmac.5 info"

# step 6: dpmac.6 info
# expect: zero exit; the dpmac attributes. dpmac.6 is a lifecycle-safe unwired port (ADR-0003 §4 port matrix), read only
run 6 restool dpmac info dpmac.6
expect_zero 6 "dpmac.6 info"

# step 7: dpmac.8 info
# expect: zero exit; the dpmac attributes. dpmac.8 is a lifecycle-safe unwired port (ADR-0003 §4 port matrix), read only
run 7 restool dpmac info dpmac.8
expect_zero 7 "dpmac.8 info"

# step 8: dpmac.10 info
# expect: zero exit; the dpmac attributes. dpmac.10 is a lifecycle-safe unwired port (ADR-0003 §4 port matrix), read only
run 8 restool dpmac info dpmac.10
expect_zero 8 "dpmac.10 info"

# step 9: shipped compiler dry-run on the reference intent
# expect: zero exit; the shipped read then compile then reconcile path over the reference intent (design D12 — the diff exercises the shipped code path). Capture the whole plan with its provenance trees and the plan-only report
run 9 dpaa2ctl --config models/intent/scenarios/reference.toml dry-run
expect_zero 9 "shipped compiler dry-run on the reference intent"

# step 10: shipped compiler status on the reference intent
# expect: exit any; the machine drift report. A nonzero exit means the board diverges from intent and is EVIDENCE for 4.2's dispositioning (design D12 open questions), never a script failure
run 10 dpaa2ctl --config models/intent/scenarios/reference.toml status
expect_any 10 "shipped compiler status on the reference intent"

save_dmesg
echo "suite V-FIT-1 read-only fit check complete"
