#!/bin/sh
# suite: V-DPCI-2
# class: object-lifecycle-only
# generated by dpaa2-verify from models/board/V-DPCI-2/vdpci2.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-DPCI-2.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- kernel-log window ---
# A marker stamps the sitting's start in the kernel log; the teardown
# saves everything after it to dmesg.txt, so rescan markers (ADR-0008)
# and probe refusals are files, not operator memory.
KMSG="dpaa2-verify V-DPCI-2 pid $$"
echo "$KMSG start" > /dev/kmsg 2>/dev/null || true
save_dmesg() {
  dmesg 2>/dev/null | awk -v m="$KMSG start" 'w || index($0, m) { w = 1 } w' > "$RESULTS/dmesg.txt"
  [ -s "$RESULTS/dmesg.txt" ] || dmesg > "$RESULTS/dmesg.txt" 2>&1 || true
}

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# Exit status stays auxiliary evidence only; conformance is judged on
# read-back (DPNI-I6, DPMAC-I8). stderr is where restool prints the MC
# status text (e.g. `No privilege (status 0x4)`), which until now lived
# only in ADR prose, so it is kept per step in step-N-err.txt.
# keep_err N: append the last command's stderr to step-N-err.txt and still show it
keep_err() { tee -a "$RESULTS/step-$1-err.txt" < "$RESULTS/.err" >&2; }
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
run() { n="$1"; shift; echo "+ $*"; "$@" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@" 2>"$RESULTS/.err")"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>"$RESULTS/.err" || true; keep_err "$n"; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpci_17:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpci_17}/driver" ] && echo "${OBJ_dpci_17}" > "/sys/bus/fsl-mc/devices/${OBJ_dpci_17}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_17:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpci_17}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_17:-}" ] && restool dpci destroy "${OBJ_dpci_17}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_16:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpci_16}/driver" ] && echo "${OBJ_dpci_16}" > "/sys/bus/fsl-mc/devices/${OBJ_dpci_16}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_16:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpci_16}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_16:-}" ] && restool dpci destroy "${OBJ_dpci_16}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_15:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_15}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_15:-}" ] && restool dpci destroy "${OBJ_dpci_15}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_14:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_14}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_14:-}" ] && restool dpci destroy "${OBJ_dpci_14}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_13:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_13}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_13:-}" ] && restool dpci destroy "${OBJ_dpci_13}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_12:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_12}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_12:-}" ] && restool dpci destroy "${OBJ_dpci_12}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_11:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_11}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_11:-}" ] && restool dpci destroy "${OBJ_dpci_11}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_10:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_10}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_10:-}" ] && restool dpci destroy "${OBJ_dpci_10}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_9:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_9}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_9:-}" ] && restool dpci destroy "${OBJ_dpci_9}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_8:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_8}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_8:-}" ] && restool dpci destroy "${OBJ_dpci_8}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_7:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_7}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_7:-}" ] && restool dpci destroy "${OBJ_dpci_7}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_6:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_6}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_6:-}" ] && restool dpci destroy "${OBJ_dpci_6}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_5:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_5}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_5:-}" ] && restool dpci destroy "${OBJ_dpci_5}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_4:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_4}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_4:-}" ] && restool dpci destroy "${OBJ_dpci_4}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_3:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_3}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_3:-}" ] && restool dpci destroy "${OBJ_dpci_3}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_2:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_2}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_2:-}" ] && restool dpci destroy "${OBJ_dpci_2}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_1:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_1}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_1:-}" ] && restool dpci destroy "${OBJ_dpci_1}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpci_0:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpci_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpci_0:-}" ] && restool dpci destroy "${OBJ_dpci_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dprc_2:-}" ] && restool dprc destroy "${OBJ_dprc_2}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  save_dmesg
}
trap teardown EXIT

# step 0: CreateContainer { parent: ObjRef { fam: Dprc, num: 1 } }
OBJ_dprc_2="$(run_create 0 restool --script dprc create dprc.1)"
echo "dprc_2 ${OBJ_dprc_2}" >> "$RESULTS/created.txt"
# expect: dprc_2 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_0="$(run_create 1 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_0 ${OBJ_dpci_0}" >> "$RESULTS/created.txt"
# expect: dpci_0 present=true plugged=false
probe 1 0 restool dprc show ${OBJ_dprc_2}

# step 2: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_1="$(run_create 2 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_1 ${OBJ_dpci_1}" >> "$RESULTS/created.txt"
# expect: dpci_1 present=true plugged=false
probe 2 0 restool dprc show ${OBJ_dprc_2}

# step 3: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_2="$(run_create 3 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_2 ${OBJ_dpci_2}" >> "$RESULTS/created.txt"
# expect: dpci_2 present=true plugged=false
probe 3 0 restool dprc show ${OBJ_dprc_2}

# step 4: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_3="$(run_create 4 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_3 ${OBJ_dpci_3}" >> "$RESULTS/created.txt"
# expect: dpci_3 present=true plugged=false
probe 4 0 restool dprc show ${OBJ_dprc_2}

# step 5: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_4="$(run_create 5 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_4 ${OBJ_dpci_4}" >> "$RESULTS/created.txt"
# expect: dpci_4 present=true plugged=false
probe 5 0 restool dprc show ${OBJ_dprc_2}

# step 6: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_5="$(run_create 6 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_5 ${OBJ_dpci_5}" >> "$RESULTS/created.txt"
# expect: dpci_5 present=true plugged=false
probe 6 0 restool dprc show ${OBJ_dprc_2}

# step 7: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_6="$(run_create 7 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_6 ${OBJ_dpci_6}" >> "$RESULTS/created.txt"
# expect: dpci_6 present=true plugged=false
probe 7 0 restool dprc show ${OBJ_dprc_2}

# step 8: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_7="$(run_create 8 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_7 ${OBJ_dpci_7}" >> "$RESULTS/created.txt"
# expect: dpci_7 present=true plugged=false
probe 8 0 restool dprc show ${OBJ_dprc_2}

# step 9: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_8="$(run_create 9 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_8 ${OBJ_dpci_8}" >> "$RESULTS/created.txt"
# expect: dpci_8 present=true plugged=false
probe 9 0 restool dprc show ${OBJ_dprc_2}

# step 10: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_9="$(run_create 10 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_9 ${OBJ_dpci_9}" >> "$RESULTS/created.txt"
# expect: dpci_9 present=true plugged=false
probe 10 0 restool dprc show ${OBJ_dprc_2}

# step 11: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_10="$(run_create 11 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_10 ${OBJ_dpci_10}" >> "$RESULTS/created.txt"
# expect: dpci_10 present=true plugged=false
probe 11 0 restool dprc show ${OBJ_dprc_2}

# step 12: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_11="$(run_create 12 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_11 ${OBJ_dpci_11}" >> "$RESULTS/created.txt"
# expect: dpci_11 present=true plugged=false
probe 12 0 restool dprc show ${OBJ_dprc_2}

# step 13: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_12="$(run_create 13 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_12 ${OBJ_dpci_12}" >> "$RESULTS/created.txt"
# expect: dpci_12 present=true plugged=false
probe 13 0 restool dprc show ${OBJ_dprc_2}

# step 14: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_13="$(run_create 14 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_13 ${OBJ_dpci_13}" >> "$RESULTS/created.txt"
# expect: dpci_13 present=true plugged=false
probe 14 0 restool dprc show ${OBJ_dprc_2}

# step 15: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_14="$(run_create 15 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_14 ${OBJ_dpci_14}" >> "$RESULTS/created.txt"
# expect: dpci_14 present=true plugged=false
probe 15 0 restool dprc show ${OBJ_dprc_2}

# step 16: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpci_15="$(run_create 16 restool --script dpci create --num-priorities=2 --container=${OBJ_dprc_2})"
echo "dpci_15 ${OBJ_dpci_15}" >> "$RESULTS/created.txt"
# expect: dpci_15 present=true plugged=false
probe 16 0 restool dprc show ${OBJ_dprc_2}

# step 17: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpci_16="$(run_create 17 restool --script dpci create --num-priorities=2 --container=dprc.1)"
echo "dpci_16 ${OBJ_dpci_16}" >> "$RESULTS/created.txt"
# expect: dpci_16 present=true plugged=false
probe 17 0 restool dprc show dprc.1

# step 18: CreateObject { fam: Dpci, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpci_17="$(run_create 18 restool --script dpci create --num-priorities=2 --container=dprc.1)"
echo "dpci_17 ${OBJ_dpci_17}" >> "$RESULTS/created.txt"
# expect: dpci_17 present=true plugged=false
probe 18 0 restool dprc show dprc.1

# step 19: ConnectEdge { a: EndpointRef { obj: ObjRef { fam: Dpci, num: 16 }, port: 0 }, b: EndpointRef { obj: ObjRef { fam: Dpci, num: 17 }, port: 0 } }
run 19 restool dprc connect dprc.1 --endpoint1=${OBJ_dpci_16} --endpoint2=${OBJ_dpci_17}
# expect: dpci_16 endpoint=dpci_17 link=down
probe 19 0 restool dpci info ${OBJ_dpci_16}

# --- suite hook: models/board/V-DPCI-2/pair.sh ---
# Hand-written steps that need the created objects standing; sourced so
# they see this script's variables and run under the teardown trap.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "models/board/V-DPCI-2/pair.sh" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in the hook" >&2  # safety-self-check
  exit 1
fi
. "models/board/V-DPCI-2/pair.sh"

echo "suite V-DPCI-2 complete"
