#!/bin/sh
# suite: V-TRAF-0
# class: traffic-bearing  (explicitly flagged run)
# generated by dpaa2-verify from models/board/V-TRAF-0/vtraf0.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-TRAF-0.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
# Exit status is recorded as auxiliary evidence only; conformance is
# judged on read-back (DPNI-I6, DPMAC-I8).
run() { n="$1"; shift; echo "+ $*"; "$@"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@")"; echo $? >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpni_2:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_2}/driver" ] && echo "${OBJ_dpni_2}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_2}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_2:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpni_2}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_2:-}" ] && restool dpni destroy "${OBJ_dpni_2}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpcon_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpcon_0}/driver" ] && echo "${OBJ_dpcon_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpcon_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpcon_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpcon_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpcon_0:-}" ] && restool dpcon destroy "${OBJ_dpcon_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpbp_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpbp_0}/driver" ] && echo "${OBJ_dpbp_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpbp_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpbp_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpbp_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpbp_0:-}" ] && restool dpbp destroy "${OBJ_dpbp_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpmcp_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_0}/driver" ] && echo "${OBJ_dpmcp_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpmcp_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_0:-}" ] && restool dpmcp destroy "${OBJ_dpmcp_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  # restore boot wiring severed by this suite (reference-environment edge)
  restool dprc connect dprc.1 --endpoint1=dpni.1 --endpoint2=dpmac.7 2>>"$RESULTS/teardown.log"
  sleep 2
}
trap teardown EXIT

# step 0: DisconnectEdge { e: EndpointRef { obj: ObjRef { fam: Dpni, num: 1 }, port: 0 } }
run 0 restool dprc disconnect dprc.1 --endpoint=dpni.1
# expect: dpni_1 endpoint=none
probe 0 0 restool dpni info dpni.1

# step 1: CreateObject { fam: Dpmcp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpmcp_0="$(run_create 1 restool --script dpmcp create --container=dprc.1)"
echo "dpmcp_0 ${OBJ_dpmcp_0}" >> "$RESULTS/created.txt"
# expect: dpmcp_0 present=true plugged=false
probe 1 0 restool dprc show dprc.1

# step 2: CreateObject { fam: Dpbp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpbp_0="$(run_create 2 restool --script dpbp create --container=dprc.1)"
echo "dpbp_0 ${OBJ_dpbp_0}" >> "$RESULTS/created.txt"
# expect: dpbp_0 present=true plugged=false
probe 2 0 restool dprc show dprc.1

# step 3: CreateObject { fam: Dpcon, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpcon_0="$(run_create 3 restool --script dpcon create --num-priorities=2 --container=dprc.1)"
echo "dpcon_0 ${OBJ_dpcon_0}" >> "$RESULTS/created.txt"
# expect: dpcon_0 present=true plugged=false
probe 3 0 restool dprc show dprc.1

# step 4: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_2="$(run_create 4 restool --script dpni create --container=dprc.1)"
echo "dpni_2 ${OBJ_dpni_2}" >> "$RESULTS/created.txt"
# expect: dpni_2 present=true plugged=false
probe 4 0 restool dprc show dprc.1

# step 5: ConnectEdge { a: EndpointRef { obj: ObjRef { fam: Dpni, num: 2 }, port: 0 }, b: EndpointRef { obj: ObjRef { fam: Dpmac, num: 7 }, port: 0 } }
run 5 restool dprc connect dprc.1 --endpoint1=${OBJ_dpni_2} --endpoint2=dpmac.7
# expect: dpni_2 endpoint=dpmac_7 link=down
probe 5 0 restool dpni info ${OBJ_dpni_2}

# step 6: Plug { obj: ObjRef { fam: Dpmcp, num: 0 } }
run 6 restool dprc assign dprc.1 --object=${OBJ_dpmcp_0} --plugged=1
# expect: dpmcp_0 present=true plugged=true
probe 6 0 restool dprc show dprc.1

# step 7: Plug { obj: ObjRef { fam: Dpbp, num: 0 } }
run 7 restool dprc assign dprc.1 --object=${OBJ_dpbp_0} --plugged=1
# expect: dpbp_0 present=true plugged=true
probe 7 0 restool dprc show dprc.1

# step 8: Plug { obj: ObjRef { fam: Dpcon, num: 0 } }
run 8 restool dprc assign dprc.1 --object=${OBJ_dpcon_0} --plugged=1
# expect: dpcon_0 present=true plugged=true
probe 8 0 restool dprc show dprc.1

# step 9: Plug { obj: ObjRef { fam: Dpni, num: 2 } }
run 9 restool dprc assign dprc.1 --object=${OBJ_dpni_2} --plugged=1
# expect: dpni_2 present=true plugged=true
probe 9 0 restool dprc show dprc.1

# step 10: Rescan { container: ObjRef { fam: Dprc, num: 1 } }
run 10 restool dprc sync

# step 11: KernelBind { obj: ObjRef { fam: Dpni, num: 2 } }
# awaited: the kernel probes plugged bus-visible objects on its own; observe the driver link
sleep 1
# expect: dpni_2 driver_bound=true
probe_link 11 0 /sys/bus/fsl-mc/devices/${OBJ_dpni_2}/driver

# step 12: Enable { obj: ObjRef { fam: Dpni, num: 2 } }
# awaited: enable is always consumer-side; restool enables nothing (§5 step 7)
printf '>> operator action: %s\n' "bring the consumer up: find the netdev under /sys/bus/fsl-mc/devices/${OBJ_dpni_2}/net/ and ip link set <it> up"
printf '   press enter when done: '
read -r _ack

# step 13: LinkChange { obj: ObjRef { fam: Dpni, num: 2 } }
# awaited: PHY reality; link-signaling scenarios observe it, nothing drives it
printf '>> operator action: %s\n' "restore the link facing dpmac.7 (reinsert the cable), then verify both faces: cat /sys/class/net/<netdev>/carrier reads 1 (the netdev is under /sys/bus/fsl-mc/devices/${OBJ_dpni_2}/net/) and restool dpni info ${OBJ_dpni_2} shows link status: 1, and only then press enter"
printf '   press enter when done: '
read -r _ack
# expect: dpni_2 present=true link=up
probe 13 0 restool dpni info ${OBJ_dpni_2}
probe 13 1 restool dpmac info dpmac.7

# --- suite hook: models/board/V-TRAF-0/traffic.sh ---
# Hand-written steps that need the created objects standing; sourced so
# they see this script's variables and run under the teardown trap.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "models/board/V-TRAF-0/traffic.sh" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in the hook" >&2  # safety-self-check
  exit 1
fi
. "models/board/V-TRAF-0/traffic.sh"

echo "suite V-TRAF-0 complete"
