#!/bin/sh
# suite: V-DPDMUX-2
# class: object-lifecycle-only
# generated by dpaa2-verify from models/board/V-DPDMUX-2/vdpdmux2.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-DPDMUX-2.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- kernel-log window ---
# A marker stamps the sitting's start in the kernel log; the teardown
# saves everything after it to dmesg.txt, so rescan markers (ADR-0008)
# and probe refusals are files, not operator memory.
KMSG="dpaa2-verify V-DPDMUX-2 pid $$"
echo "$KMSG start" > /dev/kmsg 2>/dev/null || true
save_dmesg() {
  dmesg 2>/dev/null | awk -v m="$KMSG start" 'w || index($0, m) { w = 1 } w' > "$RESULTS/dmesg.txt"
  [ -s "$RESULTS/dmesg.txt" ] || dmesg > "$RESULTS/dmesg.txt" 2>&1 || true
}

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# Exit status stays auxiliary evidence only; conformance is judged on
# read-back (DPNI-I6, DPMAC-I8). stderr is where restool prints the MC
# status text (e.g. `No privilege (status 0x4)`), which until now lived
# only in ADR prose, so it is kept per step in step-N-err.txt.
# keep_err N: append the last command's stderr to step-N-err.txt and still show it
keep_err() { tee -a "$RESULTS/step-$1-err.txt" < "$RESULTS/.err" >&2; }
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
run() { n="$1"; shift; echo "+ $*"; "$@" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@" 2>"$RESULTS/.err")"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>"$RESULTS/.err" || true; keep_err "$n"; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpni_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_0}/driver" ] && echo "${OBJ_dpni_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpni_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_0:-}" ] && restool dpni destroy "${OBJ_dpni_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpdmux_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpdmux_0}/driver" ] && echo "${OBJ_dpdmux_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpdmux_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpdmux_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpdmux_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpdmux_0:-}" ] && restool dpdmux destroy "${OBJ_dpdmux_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  save_dmesg
}
trap teardown EXIT

# step 0: CreateObject { fam: Dpdmux, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpdmux_0="$(run_create 0 restool --script dpdmux create --num-ifs=1 --container=dprc.1)"
echo "dpdmux_0 ${OBJ_dpdmux_0}" >> "$RESULTS/created.txt"
# expect: dpdmux_0 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_0="$(run_create 1 restool --script dpni create --container=dprc.1)"
echo "dpni_0 ${OBJ_dpni_0}" >> "$RESULTS/created.txt"
# expect: dpni_0 present=true plugged=false
probe 1 0 restool dprc show dprc.1

# --- suite hook: models/board/V-DPDMUX-2/uplink.sh ---
# Hand-written steps that need the created objects standing; sourced so
# they see this script's variables and run under the teardown trap.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "models/board/V-DPDMUX-2/uplink.sh" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in the hook" >&2  # safety-self-check
  exit 1
fi
. "models/board/V-DPDMUX-2/uplink.sh"

echo "suite V-DPDMUX-2 complete"
