#!/bin/sh
# suite: V-DPSW-4
# class: object-lifecycle-only
# generated by dpaa2-verify from models/board/V-DPSW-4/vdpsw4.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-DPSW-4.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- kernel-log window ---
# A marker stamps the sitting's start in the kernel log; the teardown
# saves everything after it to dmesg.txt, so rescan markers (ADR-0008)
# and probe refusals are files, not operator memory.
KMSG="dpaa2-verify V-DPSW-4 pid $$"
echo "$KMSG start" > /dev/kmsg 2>/dev/null || true
save_dmesg() {
  dmesg 2>/dev/null | awk -v m="$KMSG start" 'w || index($0, m) { w = 1 } w' > "$RESULTS/dmesg.txt"
  [ -s "$RESULTS/dmesg.txt" ] || dmesg > "$RESULTS/dmesg.txt" 2>&1 || true
}

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# Exit status stays auxiliary evidence only; conformance is judged on
# read-back (DPNI-I6, DPMAC-I8). stderr is where restool prints the MC
# status text (e.g. `No privilege (status 0x4)`), which until now lived
# only in ADR prose, so it is kept per step in step-N-err.txt.
# keep_err N: append the last command's stderr to step-N-err.txt and still show it
keep_err() { tee -a "$RESULTS/step-$1-err.txt" < "$RESULTS/.err" >&2; }
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
run() { n="$1"; shift; echo "+ $*"; "$@" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@" 2>"$RESULTS/.err")"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>"$RESULTS/.err" || true; keep_err "$n"; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpsw_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpsw_0}/driver" ] && echo "${OBJ_dpsw_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpsw_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpsw_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpsw_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpsw_0:-}" ] && restool dpsw destroy "${OBJ_dpsw_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpbp_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpbp_0}/driver" ] && echo "${OBJ_dpbp_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpbp_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpbp_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpbp_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpbp_0:-}" ] && restool dpbp destroy "${OBJ_dpbp_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpmcp_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_0}/driver" ] && echo "${OBJ_dpmcp_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpmcp_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_0:-}" ] && restool dpmcp destroy "${OBJ_dpmcp_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  save_dmesg
}
trap teardown EXIT

# step 0: CreateObject { fam: Dpmcp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpmcp_0="$(run_create 0 restool --script dpmcp create --container=dprc.1)"
echo "dpmcp_0 ${OBJ_dpmcp_0}" >> "$RESULTS/created.txt"
# expect: dpmcp_0 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateObject { fam: Dpbp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpbp_0="$(run_create 1 restool --script dpbp create --container=dprc.1)"
echo "dpbp_0 ${OBJ_dpbp_0}" >> "$RESULTS/created.txt"
# expect: dpbp_0 present=true plugged=false
probe 1 0 restool dprc show dprc.1

# step 2: CreateObject { fam: Dpsw, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpsw_0="$(run_create 2 restool --script dpsw create --num-ifs=2 --container=dprc.1)"
echo "dpsw_0 ${OBJ_dpsw_0}" >> "$RESULTS/created.txt"
# expect: dpsw_0 present=true plugged=false
probe 2 0 restool dprc show dprc.1

# step 3: ConnectEdge { a: EndpointRef { obj: ObjRef { fam: Dpsw, num: 0 }, port: 0 }, b: EndpointRef { obj: ObjRef { fam: Dpmac, num: 5 }, port: 0 } }
run 3 restool dprc connect dprc.1 --endpoint1=${OBJ_dpsw_0} --endpoint2=dpmac.5
# expect: dpsw_0 endpoint=dpmac_5
probe 3 0 restool dpsw info ${OBJ_dpsw_0}

# step 4: Plug { obj: ObjRef { fam: Dpmcp, num: 0 } }
run 4 restool dprc assign dprc.1 --object=${OBJ_dpmcp_0} --plugged=1
# expect: dpmcp_0 present=true plugged=true
probe 4 0 restool dprc show dprc.1

# step 5: Plug { obj: ObjRef { fam: Dpbp, num: 0 } }
run 5 restool dprc assign dprc.1 --object=${OBJ_dpbp_0} --plugged=1
# expect: dpbp_0 present=true plugged=true
probe 5 0 restool dprc show dprc.1

# step 6: Plug { obj: ObjRef { fam: Dpsw, num: 0 } }
run 6 restool dprc assign dprc.1 --object=${OBJ_dpsw_0} --plugged=1
# expect: dpsw_0 present=true plugged=true
probe 6 0 restool dprc show dprc.1

# step 7: Rescan { container: ObjRef { fam: Dprc, num: 1 } }
run 7 restool dprc sync

# --- suite hook: models/board/V-DPSW-4/refusal.sh ---
# Hand-written steps that need the created objects standing; sourced so
# they see this script's variables and run under the teardown trap.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "models/board/V-DPSW-4/refusal.sh" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in the hook" >&2  # safety-self-check
  exit 1
fi
. "models/board/V-DPSW-4/refusal.sh"

echo "suite V-DPSW-4 complete"
