#!/bin/sh
# suite: V-DPDMAI-2
# class: object-lifecycle-only
# generated by dpaa2-verify from models/board/V-DPDMAI-2/vdpdmai2.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-DPDMAI-2.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- kernel-log window ---
# A marker stamps the sitting's start in the kernel log; the teardown
# saves everything after it to dmesg.txt, so rescan markers (ADR-0008)
# and probe refusals are files, not operator memory.
KMSG="dpaa2-verify V-DPDMAI-2 pid $$"
echo "$KMSG start" > /dev/kmsg 2>/dev/null || true
save_dmesg() {
  dmesg 2>/dev/null | awk -v m="$KMSG start" 'w || index($0, m) { w = 1 } w' > "$RESULTS/dmesg.txt"
  [ -s "$RESULTS/dmesg.txt" ] || dmesg > "$RESULTS/dmesg.txt" 2>&1 || true
}

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# Exit status stays auxiliary evidence only; conformance is judged on
# read-back (DPNI-I6, DPMAC-I8). stderr is where restool prints the MC
# status text (e.g. `No privilege (status 0x4)`), which until now lived
# only in ADR prose, so it is kept per step in step-N-err.txt.
# keep_err N: append the last command's stderr to step-N-err.txt and still show it
keep_err() { tee -a "$RESULTS/step-$1-err.txt" < "$RESULTS/.err" >&2; }
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
run() { n="$1"; shift; echo "+ $*"; "$@" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@" 2>"$RESULTS/.err")"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>"$RESULTS/.err" || true; keep_err "$n"; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- pre-state capture (recovery check runs first) ---
# Take this suite from a fresh boot with no MC-mutating services
# started: the pre-state is the recovery-diff reference, so it must
# itself be the boot state.
restool dprc list                > "$RESULTS/pre-dprc-list.txt"
restool dprc show dprc.1         > "$RESULTS/pre-dprc1-show.txt"
restool dprc generate-dpl dprc.1 > "$RESULTS/pre-dpl.dts"

# step 0: CreateObject { fam: Dpdmai, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpdmai_0="$(run_create 0 restool --script dpdmai create --container=dprc.1)"
echo "dpdmai_0 ${OBJ_dpdmai_0}" >> "$RESULTS/created.txt"
# expect: dpdmai_0 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# --- no teardown: the reboot is the teardown (ADR-0003 §7) ---
# The scratch set above is deliberately left in place. Now:
#   1. reboot the board
#   2. run V-DPDMAI-2-postboot.sh with the same results directory
save_dmesg
echo "suite V-DPDMAI-2 mutations complete - scratch set left in place; reboot now"
