#!/bin/sh
# suite: V-READBACK-1
# class: object-lifecycle-only
# generated by dpaa2-verify from models/board/V-READBACK-1/vreadback1.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-READBACK-1.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
# Exit status is recorded as auxiliary evidence only; conformance is
# judged on read-back (DPNI-I6, DPMAC-I8).
run() { n="$1"; shift; echo "+ $*"; "$@"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@")"; echo $? >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpdcei_0:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpdcei_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpdcei_0:-}" ] && restool dpdcei destroy "${OBJ_dpdcei_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpbp_0:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpbp_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpbp_0:-}" ] && restool dpbp destroy "${OBJ_dpbp_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpio_0:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpio_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpio_0:-}" ] && restool dpio destroy "${OBJ_dpio_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpdmai_0:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpdmai_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpdmai_0:-}" ] && restool dpdmai destroy "${OBJ_dpdmai_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_0:-}" ] && restool dprc assign ${OBJ_dprc_2} --object="${OBJ_dpni_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_0:-}" ] && restool dpni destroy "${OBJ_dpni_0}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dprc_2:-}" ] && restool dprc destroy "${OBJ_dprc_2}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
}
trap teardown EXIT

# step 0: CreateContainer { parent: ObjRef { fam: Dprc, num: 1 } }
OBJ_dprc_2="$(run_create 0 restool --script dprc create dprc.1)"
echo "dprc_2 ${OBJ_dprc_2}" >> "$RESULTS/created.txt"
# expect: dprc_2 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpni_0="$(run_create 1 restool --script dpni create --container=${OBJ_dprc_2})"
echo "dpni_0 ${OBJ_dpni_0}" >> "$RESULTS/created.txt"
# expect: dpni_0 present=true plugged=false
probe 1 0 restool dprc show ${OBJ_dprc_2}

# step 2: CreateObject { fam: Dpdmai, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpdmai_0="$(run_create 2 restool --script dpdmai create --container=${OBJ_dprc_2})"
echo "dpdmai_0 ${OBJ_dpdmai_0}" >> "$RESULTS/created.txt"
# expect: dpdmai_0 present=true plugged=false
probe 2 0 restool dprc show ${OBJ_dprc_2}

# step 3: CreateObject { fam: Dpio, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpio_0="$(run_create 3 restool --script dpio create --channel-mode=DPIO_NO_CHANNEL --num-priorities=8 --container=${OBJ_dprc_2})"
echo "dpio_0 ${OBJ_dpio_0}" >> "$RESULTS/created.txt"
# expect: dpio_0 present=true plugged=false
probe 3 0 restool dprc show ${OBJ_dprc_2}

# step 4: CreateObject { fam: Dpbp, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpbp_0="$(run_create 4 restool --script dpbp create --container=${OBJ_dprc_2})"
echo "dpbp_0 ${OBJ_dpbp_0}" >> "$RESULTS/created.txt"
# expect: dpbp_0 present=true plugged=false
probe 4 0 restool dprc show ${OBJ_dprc_2}

# step 5: CreateObject { fam: Dpdcei, container: ObjRef { fam: Dprc, num: 2 } }
OBJ_dpdcei_0="$(run_create 5 restool --script dpdcei create --engine=DPDCEI_ENGINE_DECOMPRESSION --priority=1 --container=${OBJ_dprc_2})"
echo "dpdcei_0 ${OBJ_dpdcei_0}" >> "$RESULTS/created.txt"
# expect: dpdcei_0 present=true plugged=false
probe 5 0 restool dprc show ${OBJ_dprc_2}

# --- suite hook: models/board/V-READBACK-1/readback.sh ---
# Hand-written steps that need the created objects standing; sourced so
# they see this script's variables and run under the teardown trap.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "models/board/V-READBACK-1/readback.sh" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in the hook" >&2  # safety-self-check
  exit 1
fi
. "models/board/V-READBACK-1/readback.sh"

echo "suite V-READBACK-1 complete"
