//! Board snapshot: a read-only census of the whole MC container tree,
//! reduced to a deterministic, diffable JSON so a sitting can be shown to
//! have left no residue (task 6.3).
//!
//! Three subcommands, each pure:
//!
//! - [`render`] emits the capture script — a `sh` walk that lists every
//!   container, reads every object back with `restool <fam> info`, follows
//!   each object's sysfs driver link, records the three reference versions
//!   and the `generate-dpl` topology. It carries the same independent
//!   total-deny self-check and reference-pair assertion every generated
//!   suite does (shared with [`crate::generate`]), and names no object
//!   literally — every name comes from a loop over the live tree, so the
//!   script can never reference a total-deny object.
//! - [`parse`] folds one capture directory into a [`Snapshot`].
//! - [`diff`] reports the deltas between two snapshots, one human line
//!   each, in a deterministic order.
//!
//! Redaction: the only board text that carries identifying information is
//! a MAC address, so any whitespace-delimited `hh:hh:hh:hh:hh:hh` token in
//! any captured value, label or `mc.global` dump is masked to
//! `xx:xx:xx:xx:xx:xx`. Nothing else is: the kernel string is `uname -r`
//! by construction (no build-host, unlike `uname -a`), and restool's
//! `info` output carries no hostnames. Traffic counters (the dpni
//! statistics block and the dpmac `Counters:` block) are dropped so the
//! snapshot records state, never traffic, and two captures diff clean.
//! The committed clean-boot reference lives at
//! `models/board/baselines/reference.json`; the operator captures it, so
//! it is not generated here.

use std::collections::{BTreeMap, BTreeSet};

use crate::generate::{REF_PAIR_ASSERT, TOTAL_DENY_GREP};

/// The three stamped reference versions of a capture.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Versions {
    /// The full `restool --version` line, trimmed.
    pub restool: String,
    /// The MC firmware version number only (e.g. `10.39.0`).
    pub mc_firmware: String,
    /// The kernel release (`uname -r`), trimmed.
    pub kernel: String,
}

/// One MC container (a dprc) as it sits in the tree.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Container {
    /// The parent container, or `None` for the root.
    pub parent: Option<String>,
    /// The objects this container holds, in `dprc show` order.
    pub objects: Vec<String>,
}

/// One MC object as `restool <fam> info` and sysfs report it.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Object {
    /// The container the object is listed in.
    pub container: String,
    /// The object's label in its container's `dprc show` (redacted).
    pub label: String,
    /// Whether the object is plugged.
    pub plugged: bool,
    /// The bound driver (basename of the sysfs `driver` link target), or
    /// `None` when the object holds no driver.
    pub driver: Option<String>,
    /// Every `label: value` attribute of `info`, values redacted.
    pub info: BTreeMap<String, String>,
}

/// A parsed, redacted board snapshot: the whole container tree reduced to
/// the state a sitting can change, deterministic so two captures diff.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Snapshot {
    /// The three stamped reference versions.
    pub versions: Versions,
    /// Every container, keyed by name.
    pub containers: BTreeMap<String, Container>,
    /// The raw (redacted, trimmed) `dprc show mc.global` text.
    pub mc_global: String,
    /// Every object, keyed by name.
    pub objects: BTreeMap<String, Object>,
    /// The per-family object API version (e.g. `dpni` -> `7.17`).
    pub api_versions: BTreeMap<String, String>,
    /// The DPL connection edges (`dpni.1` <-> `dpmac.7`), sorted.
    pub connections: Vec<(String, String)>,
}

/// The MAC-address mask redaction leaves behind.
const MAC_MASK: &str = "xx:xx:xx:xx:xx:xx";

/// Renders the read-only capture script.
///
/// The script is executable `sh`; give it one argument, the capture
/// directory. Its shape mirrors a generated suite's preamble — a
/// total-deny self-check over `$0` and the reference-pair assertion —
/// before it captures anything.
#[must_use]
pub fn render() -> String {
    let deny = TOTAL_DENY_GREP;
    let ref_pair = REF_PAIR_ASSERT;
    format!(
        r#"#!/bin/sh
# board snapshot — read-only: lists containers, reads every object back, driver links, versions, generate-dpl
# generated by dpaa2-verify snapshot render — do not edit; regenerate instead.
# Fold the capture into diffable JSON with:
#   dpaa2-verify snapshot parse <dir> --out snapshot.json
set -u
CAP="${{1:?usage: $0 <capture-dir>}}"
mkdir -p "$CAP"

# --- independent safety self-check (ADR-0003 §4) ---
# Refuse a total-deny reference even if this script was hand-edited.
if grep -nE '{deny}' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

{ref_pair}
# --- versions (uname -r only: no build-host strings) ---
restool --version > "$CAP/restool-version.txt" 2>&1
restool -m > "$CAP/mc-version.txt"
uname -r > "$CAP/kernel-version.txt"

# --- containers ---
restool dprc list --full-path > "$CAP/dprc-list.txt"
restool dprc show mc.global > "$CAP/show-mc.global.txt" 2>&1 || true

# --- read every container back: show, info, driver link ---
while read -r path; do
  c="${{path##*/}}"
  [ -n "$c" ] || continue
  restool dprc show "$c" > "$CAP/show-$c.txt"
  restool dprc info "$c" > "$CAP/info-$c.txt" 2>&1
  readlink "/sys/bus/fsl-mc/devices/$c/driver" > "$CAP/driver-$c.txt" 2>/dev/null || true
done < "$CAP/dprc-list.txt"

# --- read every object of every container back: info, driver link ---
for f in "$CAP"/show-*.txt; do
  [ "$f" = "$CAP/show-mc.global.txt" ] && continue
  tail -n +3 "$f" | while read -r o _rest; do
    [ -n "$o" ] || continue
    restool "${{o%%.*}}" info "$o" > "$CAP/info-$o.txt" 2>&1
    readlink "/sys/bus/fsl-mc/devices/$o/driver" > "$CAP/driver-$o.txt" 2>/dev/null || true
  done
done

# --- DPL topology (read-only query walk of live MC state) ---
restool dprc generate-dpl dprc.1 > "$CAP/dpl.dts"
echo "snapshot captured in $CAP"
"#
    )
}

/// Whether a whitespace token is a bare MAC address (`hh:hh:hh:hh:hh:hh`).
fn is_mac(tok: &str) -> bool {
    let mut pairs = 0;
    for part in tok.split(':') {
        pairs += 1;
        if part.len() != 2 || !part.bytes().all(|b| b.is_ascii_hexdigit()) {
            return false;
        }
    }
    pairs == 6
}

/// Masks every bare MAC token in a text, leaving all other text and
/// whitespace intact.
fn redact(text: &str) -> String {
    let macs: BTreeSet<&str> = text.split_whitespace().filter(|t| is_mac(t)).collect();
    let mut out = text.to_owned();
    for mac in macs {
        out = out.replace(mac, MAC_MASK);
    }
    out
}

/// Key prefixes of the dpni traffic-statistics block. These are counters,
/// not configuration: they drift with every frame on the management pair,
/// so a snapshot that carried them could never diff clean. The snapshot
/// records state, never traffic, so the diff must be blind to them. The
/// `tx_pending_frames_cnt` entry is a whole key (it matches only itself);
/// the rest are true prefixes over families of counters.
const COUNTER_PREFIXES: [&str; 6] = [
    "ingress_",
    "egress_",
    "ceetm_",
    "cgr_",
    "policer_",
    "tx_pending_frames_cnt",
];

/// Parses one `info` capture into its attribute map and, if present, the
/// `<fam> version: X.Y` line as an API-version pair.
///
/// Line shapes:
/// - A line with a colon is `key: value`, split on the first colon and
///   trimmed.
/// - A tab-indented colon-less line continues the previous key's value,
///   joined with `,` — how a header like `dpni options:` and its flag
///   lines land as one value.
/// - A colon-less line that is *not* tab-indented is an attribute of its
///   own, recorded with an empty value (e.g. dpmac's `maximum supported
///   rate 10000 Mbps`).
///
/// Counters are dropped so the diff is blind to traffic: the dpmac
/// `Counters:` header ends the useful part of the file (everything below
/// it is statistics, to end of file), any key matching [`COUNTER_PREFIXES`]
/// is skipped, and the dpni `ceetm stats …` counter-section header is
/// dropped.
fn parse_info(text: &str) -> (BTreeMap<String, String>, Option<(String, String)>) {
    let text = redact(text);
    let mut info: BTreeMap<String, String> = BTreeMap::new();
    let mut fam_ver: Option<(String, String)> = None;
    let mut last_key: Option<String> = None;
    for line in text.lines() {
        if line.trim().is_empty() {
            last_key = None;
            continue;
        }
        if let Some((key, value)) = line.split_once(':') {
            let key = key.trim().to_owned();
            let value = value.trim().to_owned();
            // The dpmac `Counters:` header ends configuration; every line
            // below it is a statistic, to end of file.
            if key == "Counters" && value.is_empty() {
                break;
            }
            // dpni statistics: drop, the diff must not see traffic.
            if COUNTER_PREFIXES.iter().any(|p| key.starts_with(p)) {
                last_key = None;
                continue;
            }
            if let Some(fam) = key.strip_suffix(" version")
                && !fam.is_empty()
                && !fam.contains(' ')
                && fam_ver.is_none()
            {
                fam_ver = Some((fam.to_owned(), value.clone()));
            }
            info.insert(key.clone(), value);
            last_key = Some(key);
        } else if line.starts_with('\t') {
            if let Some(key) = &last_key {
                let entry = info.entry(key.clone()).or_default();
                if !entry.is_empty() {
                    entry.push(',');
                }
                entry.push_str(line.trim());
            }
        } else {
            // Colon-less, not tab-indented: an attribute of its own, save
            // the dpni `ceetm stats …` counter-section header, which is
            // dropped with the statistics it introduces.
            let key = line.trim().to_owned();
            if key.starts_with("ceetm stats") {
                last_key = None;
                continue;
            }
            info.insert(key.clone(), String::new());
            last_key = Some(key);
        }
    }
    (info, fam_ver)
}

/// Extracts the DPL connection edges, `@`->`.`, sorted.
fn parse_connections(dts: &str) -> Vec<(String, String)> {
    let mut conns = Vec::new();
    let mut ep1: Option<String> = None;
    for line in dts.lines() {
        let line = line.trim();
        if let Some(v) = line
            .strip_prefix("endpoint1 = \"")
            .and_then(|s| s.strip_suffix("\";"))
        {
            ep1 = Some(v.replace('@', "."));
        } else if let Some(v) = line
            .strip_prefix("endpoint2 = \"")
            .and_then(|s| s.strip_suffix("\";"))
            && let Some(a) = ep1.take()
        {
            conns.push((a, v.replace('@', ".")));
        }
    }
    conns.sort();
    conns
}

/// Parses a capture directory into a [`Snapshot`]. `read` maps a capture
/// file name (e.g. `show-dprc.1.txt`, `info-dpni.1.txt`) to its content,
/// or `None` when the file does not exist.
///
/// # Errors
///
/// Fails when a top-level capture file is missing (`dprc-list.txt`, a
/// version file), when a listed object's `info-*`/`driver-*` file is
/// absent (an incomplete capture), or when two objects of one family
/// report conflicting API versions.
#[allow(clippy::too_many_lines)] // one linear capture-folding walk, by design
pub fn parse(read: impl Fn(&str) -> Option<String>) -> Result<Snapshot, String> {
    let read_req = |name: &str| -> Result<String, String> {
        read(name).ok_or_else(|| format!("incomplete capture: missing {name}"))
    };

    let versions = Versions {
        restool: read_req("restool-version.txt")?.trim().to_owned(),
        // `MC firmware version: 10.39.0` -> the number only.
        mc_firmware: read_req("mc-version.txt")?
            .rsplit(':')
            .next()
            .unwrap_or_default()
            .trim()
            .to_owned(),
        kernel: read_req("kernel-version.txt")?.trim().to_owned(),
    };

    let list = read_req("dprc-list.txt")?;
    let container_paths: Vec<&str> = list
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect();

    let mut containers: BTreeMap<String, Container> = BTreeMap::new();
    let mut objects: BTreeMap<String, Object> = BTreeMap::new();
    let mut api_versions: BTreeMap<String, String> = BTreeMap::new();

    // `--full-path` prints `dprc.1` / `dprc.1/dprc.2`: the basename names
    // the container, the component before it names the parent.
    for path in &container_paths {
        let name = path.rsplit('/').next().unwrap_or(path).to_owned();
        let parent = path.rsplit('/').nth(1).map(ToOwned::to_owned);
        containers.insert(
            name,
            Container {
                parent,
                objects: Vec::new(),
            },
        );
    }

    for path in &container_paths {
        let c = path.rsplit('/').next().unwrap_or(path).to_owned();
        let show = read_req(&format!("show-{c}.txt"))?;
        let mut names = Vec::new();
        // Skip the two header lines (`<dprc> contains N objects:` and the
        // `object  label  plugged-state` header); the first whitespace
        // token names the object, the last names its plugged state, and
        // anything between is the label (tab counts vary, may be empty).
        for line in show.lines().skip(2) {
            let toks: Vec<&str> = line.split_whitespace().collect();
            let Some((name, rest)) = toks.split_first() else {
                continue;
            };
            let name = (*name).to_owned();
            let plugged = rest.last().is_some_and(|s| *s == "plugged");
            let label = if rest.len() > 1 {
                redact(&rest[..rest.len() - 1].join(" "))
            } else {
                String::new()
            };

            let (info, fam_ver) = parse_info(&read_req(&format!("info-{name}.txt"))?);
            if let Some((fam, ver)) = fam_ver {
                match api_versions.get(&fam) {
                    Some(seen) if seen != &ver => {
                        return Err(format!("conflicting {fam} versions: {seen} vs {ver}"));
                    }
                    Some(_) => {}
                    None => {
                        api_versions.insert(fam, ver);
                    }
                }
            }

            let driver_raw = read_req(&format!("driver-{name}.txt"))?;
            let driver_target = driver_raw.trim();
            let driver = (!driver_target.is_empty()).then(|| {
                driver_target
                    .rsplit('/')
                    .next()
                    .unwrap_or(driver_target)
                    .to_owned()
            });

            names.push(name.clone());
            objects.insert(
                name,
                Object {
                    container: c.clone(),
                    label,
                    plugged,
                    driver,
                    info,
                },
            );
        }
        if let Some(container) = containers.get_mut(&c) {
            container.objects = names;
        }
    }

    let mc_global = read("show-mc.global.txt")
        .map(|s| redact(s.trim()))
        .unwrap_or_default();
    let connections = read("dpl.dts")
        .map(|s| parse_connections(&s))
        .unwrap_or_default();

    Ok(Snapshot {
        versions,
        containers,
        mc_global,
        objects,
        api_versions,
        connections,
    })
}

/// The sorted union of two maps' keys.
fn union_keys<V>(a: &BTreeMap<String, V>, b: &BTreeMap<String, V>) -> Vec<String> {
    let mut keys: BTreeSet<&String> = BTreeSet::new();
    keys.extend(a.keys());
    keys.extend(b.keys());
    keys.into_iter().cloned().collect()
}

/// Renders an optional value, `(none)` when absent.
fn some_or_none(v: Option<&String>) -> &str {
    v.map_or("(none)", String::as_str)
}

/// Appends the per-field deltas of one object present in both snapshots.
fn diff_object(name: &str, old: &Object, new: &Object, out: &mut Vec<String>) {
    if old.container != new.container {
        out.push(format!(
            "~ {name} container: {} -> {}",
            old.container, new.container
        ));
    }
    if old.label != new.label {
        out.push(format!("~ {name} label: {} -> {}", old.label, new.label));
    }
    if old.plugged != new.plugged {
        out.push(format!(
            "~ {name} plugged: {} -> {}",
            old.plugged, new.plugged
        ));
    }
    if old.driver != new.driver {
        out.push(format!(
            "~ {name} driver: {} -> {}",
            some_or_none(old.driver.as_ref()),
            some_or_none(new.driver.as_ref())
        ));
    }
    for key in union_keys(&old.info, &new.info) {
        match (old.info.get(&key), new.info.get(&key)) {
            (Some(_), None) => out.push(format!("- {name} {key}")),
            (None, Some(nv)) => out.push(format!("+ {name} {key}: {nv}")),
            (Some(ov), Some(nv)) if ov != nv => {
                out.push(format!("~ {name} {key}: {ov} -> {nv}"));
            }
            _ => {}
        }
    }
}

/// Reports the deltas from snapshot `a` to snapshot `b`, one human line
/// each, in a deterministic order (versions, containers, objects, API
/// versions, connections, then `mc.global`).
#[must_use]
pub fn diff(a: &Snapshot, b: &Snapshot) -> Vec<String> {
    let mut out = Vec::new();

    if a.versions.restool != b.versions.restool {
        out.push(format!(
            "~ versions.restool: {} -> {}",
            a.versions.restool, b.versions.restool
        ));
    }
    if a.versions.mc_firmware != b.versions.mc_firmware {
        out.push(format!(
            "~ versions.mc_firmware: {} -> {}",
            a.versions.mc_firmware, b.versions.mc_firmware
        ));
    }
    if a.versions.kernel != b.versions.kernel {
        out.push(format!(
            "~ versions.kernel: {} -> {}",
            a.versions.kernel, b.versions.kernel
        ));
    }

    for c in union_keys(&a.containers, &b.containers) {
        match (a.containers.get(&c), b.containers.get(&c)) {
            (Some(_), None) => out.push(format!("- container {c}")),
            (None, Some(_)) => out.push(format!("+ container {c}")),
            (Some(x), Some(y)) if x.parent != y.parent => out.push(format!(
                "~ container {c} parent: {} -> {}",
                some_or_none(x.parent.as_ref()),
                some_or_none(y.parent.as_ref())
            )),
            _ => {}
        }
    }

    for o in union_keys(&a.objects, &b.objects) {
        match (a.objects.get(&o), b.objects.get(&o)) {
            (Some(x), None) => out.push(format!("- object {o} ({})", x.container)),
            (None, Some(y)) => out.push(format!("+ object {o} ({})", y.container)),
            (Some(x), Some(y)) => diff_object(&o, x, y, &mut out),
            (None, None) => {}
        }
    }

    for f in union_keys(&a.api_versions, &b.api_versions) {
        match (a.api_versions.get(&f), b.api_versions.get(&f)) {
            (Some(_), None) => out.push(format!("- api {f}")),
            (None, Some(y)) => out.push(format!("+ api {f}: {y}")),
            (Some(x), Some(y)) if x != y => out.push(format!("~ api {f}: {x} -> {y}")),
            _ => {}
        }
    }

    for c in &a.connections {
        if !b.connections.contains(c) {
            out.push(format!("- connection {} <-> {}", c.0, c.1));
        }
    }
    for c in &b.connections {
        if !a.connections.contains(c) {
            out.push(format!("+ connection {} <-> {}", c.0, c.1));
        }
    }

    if a.mc_global != b.mc_global {
        out.push("~ mc_global differs".to_owned());
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Asserts a script is valid shell (`sh -n` parses, no exec) — the
    /// same check the generator's tests use.
    fn sh_parses(script: &str) {
        let path = std::env::temp_dir().join(format!(
            "dpaa2-verify-snapshot-{:x}.sh",
            std::hash::BuildHasher::hash_one(&std::hash::RandomState::new(), script)
        ));
        std::fs::write(&path, script).unwrap();
        let ok = std::process::Command::new("sh")
            .arg("-n")
            .arg(&path)
            .status()
            .unwrap()
            .success();
        std::fs::remove_file(&path).ok();
        assert!(ok, "emitted script does not parse as sh");
    }

    /// Writes a fixture capture directory and returns a `read` closure
    /// over it. Uses only generic identifiers.
    fn fixture(files: &[(&str, &str)]) -> impl Fn(&str) -> Option<String> {
        let dir = std::env::temp_dir().join(format!(
            "dpaa2-verify-snapshot-fixture-{:x}",
            std::hash::BuildHasher::hash_one(&std::hash::RandomState::new(), files),
        ));
        std::fs::create_dir_all(&dir).unwrap();
        for (name, content) in files {
            std::fs::write(dir.join(name), content).unwrap();
        }
        move |name: &str| std::fs::read_to_string(dir.join(name)).ok()
    }

    #[test]
    fn render_matches_the_committed_script() {
        let committed = std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../models/board/baselines/snapshot.sh"
        ))
        .expect("committed snapshot.sh");
        assert_eq!(render(), committed);
    }

    #[test]
    fn rendered_script_parses_and_names_no_total_deny_object() {
        let s = render();
        sh_parses(&s);
        crate::safety::scan_text(&s).expect("the script names no total-deny object");
        // The reference-pair assertion comes before any capture.
        let fw = s.find("10.39.0").unwrap();
        let first_query = s.find("restool dprc").unwrap();
        assert!(fw < first_query);
    }

    /// A capture with one root container, a child container, a
    /// driver-bound dpni with a MAC, an unbound dpmac, and one DPL edge.
    fn sample_files() -> Vec<(&'static str, &'static str)> {
        vec![
            (
                "restool-version.txt",
                "restool v2.4 (commit lf-x) (MC 10.32.0 compatible)\n",
            ),
            ("mc-version.txt", "MC firmware version: 10.39.0\n"),
            ("kernel-version.txt", "6.6.52-generic\n"),
            ("dprc-list.txt", "dprc.1\ndprc.1/dprc.2\n"),
            (
                "show-dprc.1.txt",
                "dprc.1 contains 4 objects:\n\
                 object\t\tlabel\t\tplugged-state\n\
                 dpbp.0\t\t\tplugged\n\
                 dpni.1\t\tlan\t\tplugged\n\
                 dpmac.7\t\t\tplugged\n\
                 dprc.2\t\tscratch\tunplugged\n",
            ),
            (
                "show-dprc.2.txt",
                "dprc.2 contains 1 objects:\n\
                 object\t\tlabel\t\tplugged-state\n\
                 dpio.16\t\t\tplugged\n",
            ),
            (
                "show-mc.global.txt",
                "root container mac aa:bb:cc:dd:ee:ff\n",
            ),
            ("info-dpbp.0.txt", "dpbp version: 3.4\nbpid: 1\n"),
            (
                "info-dpni.1.txt",
                "dpni version: 7.17\n\
                 mac address: 02:00:00:00:00:01\n\
                 dpni options: 0x0\n\
                 \tDPNI_OPT_TX_FRM_RELEASE\n\
                 \tDPNI_OPT_NO_MAC_FILTER\n",
            ),
            ("info-dpmac.7.txt", "dpmac version: 4.6\nlink status: 1\n"),
            ("info-dprc.2.txt", "container id: 2\ndprc options: 0x5\n"),
            (
                "info-dpio.16.txt",
                "dpio version: 4.3\nchannel mode is: DPIO_LOCAL_CHANNEL\n",
            ),
            (
                "driver-dpni.1.txt",
                "../../../bus/fsl-mc/drivers/fsl_dpaa2_eth\n",
            ),
            ("driver-dpmac.7.txt", ""),
            ("driver-dpbp.0.txt", ""),
            ("driver-dprc.2.txt", ""),
            (
                "driver-dpio.16.txt",
                "../../../bus/fsl-mc/drivers/fsl_mc_dpio\n",
            ),
            (
                "dpl.dts",
                "connections {\n\tconnection@1{\n\
                 \t\tendpoint1 = \"dpni@1\";\n\
                 \t\tendpoint2 = \"dpmac@7\";\n\t};\n};\n",
            ),
        ]
    }

    #[test]
    fn parse_builds_a_redacted_snapshot() {
        let snap = parse(fixture(&sample_files())).unwrap();

        // Versions: firmware is the number only, kernel is uname -r.
        assert_eq!(snap.versions.mc_firmware, "10.39.0");
        assert_eq!(snap.versions.kernel, "6.6.52-generic");

        // Containers and their parents.
        assert_eq!(snap.containers["dprc.1"].parent, None);
        assert_eq!(snap.containers["dprc.2"].parent.as_deref(), Some("dprc.1"));
        assert_eq!(
            snap.containers["dprc.1"].objects,
            ["dpbp.0", "dpni.1", "dpmac.7", "dprc.2"]
        );

        // Five objects: the child container counts as an object too.
        assert_eq!(snap.objects.len(), 5);
        assert_eq!(snap.objects["dprc.2"].container, "dprc.1");

        // The MAC is redacted everywhere it appears.
        assert_eq!(
            snap.objects["dpni.1"].info["mac address"],
            "xx:xx:xx:xx:xx:xx"
        );
        assert!(snap.mc_global.contains("xx:xx:xx:xx:xx:xx"));
        assert!(!snap.mc_global.contains("aa:bb"));

        // The `options:` header and its tab-indented lines fold into one
        // comma-joined value.
        assert_eq!(
            snap.objects["dpni.1"].info["dpni options"],
            "0x0,DPNI_OPT_TX_FRM_RELEASE,DPNI_OPT_NO_MAC_FILTER"
        );

        // Driver: bound reports the basename, unbound is None.
        assert_eq!(
            snap.objects["dpni.1"].driver.as_deref(),
            Some("fsl_dpaa2_eth")
        );
        assert_eq!(snap.objects["dpmac.7"].driver, None);

        // API versions and the DPL edge.
        assert_eq!(snap.api_versions["dpni"], "7.17");
        assert_eq!(snap.api_versions["dpmac"], "4.6");
        assert_eq!(
            snap.connections,
            vec![("dpni.1".to_owned(), "dpmac.7".to_owned())]
        );

        // Round-trips through serde.
        let json = serde_json::to_string_pretty(&snap).unwrap();
        let back: Snapshot = serde_json::from_str(&json).unwrap();
        assert_eq!(back, snap);
    }

    #[test]
    fn diff_is_empty_on_itself_and_reports_every_delta_kind() {
        let a = parse(fixture(&sample_files())).unwrap();
        assert!(diff(&a, &a).is_empty());

        // Mutate a clone: add an object, drop a driver, change an info
        // value, remove a connection, bump the MC firmware.
        let mut b = a.clone();
        b.objects.insert(
            "dpbp.9".to_owned(),
            Object {
                container: "dprc.1".to_owned(),
                label: String::new(),
                plugged: true,
                driver: None,
                info: BTreeMap::new(),
            },
        );
        b.objects.get_mut("dpni.1").unwrap().driver = None;
        b.objects
            .get_mut("dpmac.7")
            .unwrap()
            .info
            .insert("link status".to_owned(), "0".to_owned());
        b.connections.clear();
        b.versions.mc_firmware = "10.40.0".to_owned();

        assert_eq!(
            diff(&a, &b),
            vec![
                "~ versions.mc_firmware: 10.39.0 -> 10.40.0",
                "+ object dpbp.9 (dprc.1)",
                "~ dpmac.7 link status: 1 -> 0",
                "~ dpni.1 driver: fsl_dpaa2_eth -> (none)",
                "- connection dpni.1 <-> dpmac.7",
            ]
        );
    }

    #[test]
    fn conflicting_family_versions_are_an_error() {
        let files = vec![
            ("restool-version.txt", "restool v2.4\n"),
            ("mc-version.txt", "MC firmware version: 10.39.0\n"),
            ("kernel-version.txt", "6.6.52\n"),
            ("dprc-list.txt", "dprc.1\n"),
            (
                "show-dprc.1.txt",
                "dprc.1 contains 2 objects:\n\
                 object\t\tlabel\t\tplugged-state\n\
                 dpni.1\t\t\tplugged\n\
                 dpni.2\t\t\tplugged\n",
            ),
            ("info-dpni.1.txt", "dpni version: 7.17\n"),
            ("info-dpni.2.txt", "dpni version: 7.18\n"),
            ("driver-dpni.1.txt", ""),
            ("driver-dpni.2.txt", ""),
        ];
        let err = parse(fixture(&files)).unwrap_err();
        assert!(err.contains("conflicting dpni versions"), "{err}");
    }

    #[test]
    fn counters_are_dropped_and_bare_lines_are_attributes() {
        // dpni: config attributes, then the colon-less `ceetm stats`
        // header and the counter block (ingress_/egress_/ceetm_/cgr_/
        // policer_/tx_pending_frames_cnt) — all statistics, all dropped.
        let dpni = "dpni version: 8.5\n\
             num_queues: 16\n\
             ingress_all_frames: 3150\n\
             egress_all_bytes: 369120\n\
             ceetm stats channel 0, TC 0\n\
             ceetm_dequeue_bytes: 369120\n\
             cgr_reject_frames: 0\n\
             policer_cnt_red: 0\n\
             tx_pending_frames_cnt: 0\n";
        let (info, fam_ver) = parse_info(dpni);
        assert_eq!(fam_ver, Some(("dpni".to_owned(), "8.5".to_owned())));
        // Only the two configuration attributes survive.
        assert_eq!(
            info.keys().map(String::as_str).collect::<Vec<_>>(),
            ["dpni version", "num_queues"]
        );
        assert!(!info.contains_key("ceetm stats channel 0, TC 0"));

        // dpmac: a bare (colon-less, non-indented) attribute is a key with
        // an empty value; the `Counters:` header ends the file, so its
        // rx/tx block never lands.
        let dpmac = "dpmac version: 4.10\n\
             maximum supported rate 10000 Mbps\n\
             Counters: \n\
             rx all frames: 0\n\
             tx frames ok: 0\n";
        let (info, _) = parse_info(dpmac);
        assert_eq!(info["maximum supported rate 10000 Mbps"], "");
        assert!(!info.contains_key("Counters"));
        assert!(!info.contains_key("rx all frames"));
        assert!(!info.contains_key("tx frames ok"));
    }

    #[test]
    fn committed_reference_is_the_clean_boot_baseline() {
        let json = std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../models/board/baselines/reference.json"
        ))
        .expect("committed reference.json");
        let r: Snapshot = serde_json::from_str(&json).expect("reference deserializes");

        // One container, the root, no parent.
        assert_eq!(
            r.containers.keys().map(String::as_str).collect::<Vec<_>>(),
            ["dprc.1"]
        );
        assert_eq!(r.containers["dprc.1"].parent, None);

        // Exactly 97 objects, every one in dprc.1.
        assert_eq!(r.objects.len(), 97);
        assert!(r.objects.values().all(|o| o.container == "dprc.1"));

        // Stamped versions of the clean boot.
        assert_eq!(r.versions.mc_firmware, "10.39.0");
        assert!(
            r.versions.kernel.starts_with("6.6.52"),
            "kernel: {}",
            r.versions.kernel
        );

        // The eight object families.
        assert_eq!(
            r.api_versions
                .keys()
                .map(String::as_str)
                .collect::<Vec<_>>(),
            [
                "dpbp", "dpcon", "dpio", "dpmac", "dpmcp", "dpni", "dprtc", "dpseci"
            ]
        );

        // Exactly one connection.
        assert_eq!(r.connections.len(), 1);

        // No counter survived into the baseline, and the only hex sextet
        // left in any value or label is the redaction mask (which `is_mac`
        // rejects, its bytes not being hex).
        for o in r.objects.values() {
            for key in o.info.keys() {
                assert!(
                    !COUNTER_PREFIXES.iter().any(|p| key.starts_with(p)),
                    "counter key survived: {key}"
                );
            }
            for text in o.info.values().chain(std::iter::once(&o.label)) {
                for tok in text.split_whitespace() {
                    assert!(!is_mac(tok), "un-masked MAC in baseline: {tok}");
                }
            }
        }

        // The baseline diffs clean against itself; dropping one object is
        // the only delta a removed object shows.
        assert!(diff(&r, &r).is_empty());
        let mut mutated = r.clone();
        let removed = mutated.objects.keys().next().unwrap().clone();
        mutated.objects.remove(&removed);
        let delta = diff(&r, &mutated);
        assert_eq!(delta.len(), 1, "{delta:?}");
        assert!(delta[0].starts_with("- object "), "{}", delta[0]);
    }
}
