#!/bin/sh
# suite: V-LIFE-DPDMAI-1
# class: object-lifecycle-only
# generated by dpaa2-verify from models/board/V-LIFE-DPDMAI-1/vlife_dpdmai1.itf.json — do not edit; regenerate instead.
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-LIFE-DPDMAI-1.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
# Exit status is recorded as auxiliary evidence only; conformance is
# judged on read-back (DPNI-I6, DPMAC-I8).
run() { n="$1"; shift; echo "+ $*"; "$@"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@")"; echo $? >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2"; echo $? >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpdmai_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpdmai_0}/driver" ] && echo "${OBJ_dpdmai_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpdmai_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpdmai_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpdmai_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpdmai_0:-}" ] && restool dpdmai destroy "${OBJ_dpdmai_0}" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_0:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_0}/driver" ] && echo "${OBJ_dpmcp_0}" > "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_0}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_0:-}" ] && restool dprc assign dprc.1 --object="${OBJ_dpmcp_0}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_0:-}" ] && restool dpmcp destroy "${OBJ_dpmcp_0}" 2>>"$RESULTS/teardown.log" || true
}
trap teardown EXIT

# step 0: CreateObject { fam: Dpmcp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpmcp_0="$(run_create 0 restool --script dpmcp create --container=dprc.1)"
echo "dpmcp_0 ${OBJ_dpmcp_0}" >> "$RESULTS/created.txt"
# expect: dpmcp_0 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateObject { fam: Dpdmai, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpdmai_0="$(run_create 1 restool --script dpdmai create --container=dprc.1)"
echo "dpdmai_0 ${OBJ_dpdmai_0}" >> "$RESULTS/created.txt"
# expect: dpdmai_0 present=true plugged=false
probe 1 0 restool dprc show dprc.1

# step 2: Plug { obj: ObjRef { fam: Dpmcp, num: 0 } }
run 2 restool dprc assign dprc.1 --object=${OBJ_dpmcp_0} --plugged=1
# expect: dpmcp_0 present=true plugged=true
probe 2 0 restool dprc show dprc.1

# step 3: Plug { obj: ObjRef { fam: Dpdmai, num: 0 } }
run 3 restool dprc assign dprc.1 --object=${OBJ_dpdmai_0} --plugged=1
# expect: dpdmai_0 present=true plugged=true
probe 3 0 restool dprc show dprc.1

# step 4: Rescan { container: ObjRef { fam: Dprc, num: 1 } }
run 4 restool dprc sync

# step 5: KernelBind { obj: ObjRef { fam: Dpdmai, num: 0 } }
# awaited: the kernel probes plugged bus-visible objects on its own; observe the driver link
sleep 1
# expect: dpdmai_0 driver_bound=false
probe_link 5 0 /sys/bus/fsl-mc/devices/${OBJ_dpdmai_0}/driver

echo "suite V-LIFE-DPDMAI-1 complete"
