#!/bin/sh
# board snapshot — read-only: lists containers, reads every object back, driver links, versions, generate-dpl
# generated by dpaa2-verify snapshot render — do not edit; regenerate instead.
# Fold the capture into diffable JSON with:
#   dpaa2-verify snapshot parse <dir> --out snapshot.json
set -u
CAP="${1:?usage: $0 <capture-dir>}"
mkdir -p "$CAP"

# --- independent safety self-check (ADR-0003 §4) ---
# Refuse a total-deny reference even if this script was hand-edited.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- versions (uname -r only: no build-host strings) ---
restool --version > "$CAP/restool-version.txt" 2>&1
restool -m > "$CAP/mc-version.txt"
uname -r > "$CAP/kernel-version.txt"

# --- containers ---
restool dprc list --full-path > "$CAP/dprc-list.txt"
restool dprc show mc.global > "$CAP/show-mc.global.txt" 2>&1 || true

# --- read every container back: show, info, driver link ---
while read -r path; do
  c="${path##*/}"
  [ -n "$c" ] || continue
  restool dprc show "$c" > "$CAP/show-$c.txt"
  restool dprc info "$c" > "$CAP/info-$c.txt" 2>&1
  readlink "/sys/bus/fsl-mc/devices/$c/driver" > "$CAP/driver-$c.txt" 2>/dev/null || true
done < "$CAP/dprc-list.txt"

# --- read every object of every container back: info, driver link ---
for f in "$CAP"/show-*.txt; do
  [ "$f" = "$CAP/show-mc.global.txt" ] && continue
  tail -n +3 "$f" | while read -r o _rest; do
    [ -n "$o" ] || continue
    restool "${o%%.*}" info "$o" > "$CAP/info-$o.txt" 2>&1
    readlink "/sys/bus/fsl-mc/devices/$o/driver" > "$CAP/driver-$o.txt" 2>/dev/null || true
  done
done

# --- DPL topology (read-only query walk of live MC state) ---
restool dprc generate-dpl dprc.1 > "$CAP/dpl.dts"
echo "snapshot captured in $CAP"
