#!/bin/sh
# suite: V-TRAF-1
# class: object-lifecycle-only
# generated by dpaa2-verify from models/board/V-TRAF-1/vtraf1.qnt — do not edit; regenerate instead.
# operator: run as root — 32 steps issue MC commands the kernel gates on CAP_NET_ADMIN (docs/baseline/mc-ioctl-policy.md)
# Every board-touching command is visible below; the model's expected
# post-state sits as a comment beside each step (ADR-0003 §2). Results
# are captured under the results directory for offline diffing:
#   dpaa2-verify diff --plan V-TRAF-1.plan.json --results <dir>
set -u
RESULTS="${1:?usage: $0 <results-dir>}"
mkdir -p "$RESULTS"

# --- kernel-log window ---
# A marker stamps the sitting's start in the kernel log; the teardown
# saves everything after it to dmesg.txt, so rescan markers (ADR-0008)
# and probe refusals are files, not operator memory.
KMSG="dpaa2-verify V-TRAF-1 pid $$"
echo "$KMSG start" > /dev/kmsg 2>/dev/null || true
save_dmesg() {
  dmesg 2>/dev/null | awk -v m="$KMSG start" 'w || index($0, m) { w = 1 } w' > "$RESULTS/dmesg.txt"
  [ -s "$RESULTS/dmesg.txt" ] || dmesg > "$RESULTS/dmesg.txt" 2>&1 || true
}

# --- independent safety self-check (ADR-0003 §4) ---
# The execution side refuses total-deny references even if a script was
# hand-edited after generation.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "$0" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in this script" >&2  # safety-self-check
  exit 1
fi

# --- helpers ---
# Exit status stays auxiliary evidence only; conformance is judged on
# read-back (DPNI-I6, DPMAC-I8). stderr is where restool prints the MC
# status text (e.g. `No privilege (status 0x4)`), which until now lived
# only in ADR prose, so it is kept per step in step-N-err.txt.
# keep_err N: append the last command's stderr to step-N-err.txt and still show it
keep_err() { tee -a "$RESULTS/step-$1-err.txt" < "$RESULTS/.err" >&2; }
# run N cmd...: echo, execute, append the exit code to step-N-exit.txt.
run() { n="$1"; shift; echo "+ $*"; "$@" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# run_create N cmd...: like run, but prints the created object's name.
run_create() { n="$1"; shift; echo "+ $*" >&2; out="$("$@" 2>"$RESULTS/.err")"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; echo "$out"; }
# sysfs_write N path value
sysfs_write() { n="$1"; echo "+ echo $3 > $2"; sh -c "echo $3 > $2" 2>"$RESULTS/.err"; rc=$?; keep_err "$n"; echo $rc >> "$RESULTS/step-$n-exit.txt"; }
# probe N M cmd...: capture read-back output, never fail the script.
probe() { n="$1"; m="$2"; shift 2; echo "+ (probe) $*"; "$@" > "$RESULTS/step-$n-probe-$m.txt" 2>"$RESULTS/.err" || true; keep_err "$n"; }
# probe_link N M path: capture a sysfs driver link (empty = unbound).
probe_link() { n="$1"; m="$2"; readlink "$3" > "$RESULTS/step-$n-probe-$m.txt" 2>/dev/null || true; }
# bind_settle path name: a kernel bind lands only on a bus event. Wait up
# to 10s, then ask the bus to attach the device (drivers_probe, which an
# admin-unbound device needs since dprc sync re-fires only deferred probes,
# wait 5s), then the softer dprc sync (wait 10s). Settling, not evidence.
bind_settle() { p="$1"; d="$2"; i=0; while [ "$i" -lt 10 ]; do readlink "$p" >/dev/null 2>&1 && return 0; sleep 1; i=$((i+1)); done; echo "+ (settle) bind deferred — asking the bus to probe: echo $d > drivers_probe" >&2; echo "$d" > /sys/bus/fsl-mc/drivers_probe 2>/dev/null || true; i=0; while [ "$i" -lt 5 ]; do readlink "$p" >/dev/null 2>&1 && return 0; sleep 1; i=$((i+1)); done; echo "+ (settle) still deferred — kicking the bus: restool dprc sync" >&2; restool dprc sync 1>&2 || true; i=0; while [ "$i" -lt 10 ]; do readlink "$p" >/dev/null 2>&1 && return 0; sleep 1; i=$((i+1)); done; echo "+ (settle) bind still deferred after kick" >&2; }

# --- reference pair assertion (ADR-0003 §2) ---
# Evidence is only valid against the stamped pair; refuse anything else.
mc="$(restool -m 2>/dev/null || true)"
case "$mc" in *10.39.0*) ;; *) echo "refusing: MC firmware is not 10.39.0: $mc" >&2; exit 1 ;; esac
kernel="$(uname -r)"
case "$kernel" in 6.6.52*) ;; *) echo "refusing: kernel is not 6.6.52: $kernel" >&2; exit 1 ;; esac

# --- unconditional teardown (ADR-0003 §6) ---
teardown() {
  [ -n "${OBJ_dpni_601:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_601}/driver" ] && echo '+ echo "${OBJ_dpni_601}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_601}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpni_601}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_601}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_601:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpni_601}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpni_601}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_601:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_601}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_601}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_600:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_600}/driver" ] && echo '+ echo "${OBJ_dpni_600}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_600}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpni_600}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_600}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_600:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpni_600}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpni_600}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_600:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_600}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_600}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_500:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_500}/driver" ] && echo '+ echo "${OBJ_dpni_500}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_500}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpni_500}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_500}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_500:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpni_500}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpni_500}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_500:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_500}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_500}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_401:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_401}/driver" ] && echo '+ echo "${OBJ_dpni_401}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_401}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpni_401}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_401}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_401:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpni_401}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpni_401}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_401:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_401}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_401}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_400:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver" ] && echo '+ echo "${OBJ_dpni_400}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpni_400}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_400:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpni_400}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpni_400}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_400:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_400}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_400}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpcon_400:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpcon_400}/driver" ] && echo '+ echo "${OBJ_dpcon_400}" > "/sys/bus/fsl-mc/devices/${OBJ_dpcon_400}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpcon_400}" > "/sys/bus/fsl-mc/devices/${OBJ_dpcon_400}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpcon_400:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpcon_400}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpcon_400}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpcon_400:-}" ] && echo '+ restool dpcon destroy "${OBJ_dpcon_400}"' >> "$RESULTS/teardown.log" && restool dpcon destroy "${OBJ_dpcon_400}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpbp_400:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpbp_400}/driver" ] && echo '+ echo "${OBJ_dpbp_400}" > "/sys/bus/fsl-mc/devices/${OBJ_dpbp_400}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpbp_400}" > "/sys/bus/fsl-mc/devices/${OBJ_dpbp_400}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpbp_400:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpbp_400}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpbp_400}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpbp_400:-}" ] && echo '+ restool dpbp destroy "${OBJ_dpbp_400}"' >> "$RESULTS/teardown.log" && restool dpbp destroy "${OBJ_dpbp_400}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpmcp_400:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_400}/driver" ] && echo '+ echo "${OBJ_dpmcp_400}" > "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_400}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpmcp_400}" > "/sys/bus/fsl-mc/devices/${OBJ_dpmcp_400}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_400:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpmcp_400}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpmcp_400}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpmcp_400:-}" ] && echo '+ restool dpmcp destroy "${OBJ_dpmcp_400}"' >> "$RESULTS/teardown.log" && restool dpmcp destroy "${OBJ_dpmcp_400}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_301:-}" ] && echo '+ restool dprc assign ${OBJ_dprc_303} --object="${OBJ_dpni_301}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign ${OBJ_dprc_303} --object="${OBJ_dpni_301}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_301:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_301}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_301}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_300:-}" ] && echo '+ restool dprc assign ${OBJ_dprc_302} --object="${OBJ_dpni_300}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign ${OBJ_dprc_302} --object="${OBJ_dpni_300}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_300:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_300}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_300}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dprc_303:-}" ] && echo '+ restool dprc destroy "${OBJ_dprc_303}"' >> "$RESULTS/teardown.log" && restool dprc destroy "${OBJ_dprc_303}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dprc_302:-}" ] && echo '+ restool dprc destroy "${OBJ_dprc_302}"' >> "$RESULTS/teardown.log" && restool dprc destroy "${OBJ_dprc_302}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_201:-}" ] && echo '+ restool dprc assign ${OBJ_dprc_202} --object="${OBJ_dpni_201}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign ${OBJ_dprc_202} --object="${OBJ_dpni_201}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_201:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_201}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_201}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_200:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_200}/driver" ] && echo '+ echo "${OBJ_dpni_200}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_200}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpni_200}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_200}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_200:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpni_200}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpni_200}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_200:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_200}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_200}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dprc_202:-}" ] && echo '+ restool dprc destroy "${OBJ_dprc_202}"' >> "$RESULTS/teardown.log" && restool dprc destroy "${OBJ_dprc_202}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_101:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_101}/driver" ] && echo '+ echo "${OBJ_dpni_101}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_101}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpni_101}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_101}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_101:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpni_101}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpni_101}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_101:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_101}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_101}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  [ -n "${OBJ_dpni_100:-}" ] && [ -e "/sys/bus/fsl-mc/devices/${OBJ_dpni_100}/driver" ] && echo '+ echo "${OBJ_dpni_100}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_100}/driver/unbind"' >> "$RESULTS/teardown.log" && echo "${OBJ_dpni_100}" > "/sys/bus/fsl-mc/devices/${OBJ_dpni_100}/driver/unbind" 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_100:-}" ] && echo '+ restool dprc assign dprc.1 --object="${OBJ_dpni_100}" --plugged=0' >> "$RESULTS/teardown.log" && restool dprc assign dprc.1 --object="${OBJ_dpni_100}" --plugged=0 2>>"$RESULTS/teardown.log" || true
  [ -n "${OBJ_dpni_100:-}" ] && echo '+ restool dpni destroy "${OBJ_dpni_100}"' >> "$RESULTS/teardown.log" && restool dpni destroy "${OBJ_dpni_100}" 2>>"$RESULTS/teardown.log" || true
  sleep 2
  save_dmesg
}
trap teardown EXIT

# ===== face: 1 root<->root converge =====

# step 0: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_100="$(run_create 0 restool --script dpni create --container=dprc.1)"
echo "dpni_100 ${OBJ_dpni_100}" >> "$RESULTS/created.txt"
# expect: dpni_100 present=true plugged=false
probe 0 0 restool dprc show dprc.1

# step 1: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_101="$(run_create 1 restool --script dpni create --container=dprc.1)"
echo "dpni_101 ${OBJ_dpni_101}" >> "$RESULTS/created.txt"
# expect: dpni_101 present=true plugged=false
probe 1 0 restool dprc show dprc.1

# step 2: ConnectEdge { a: EndpointRef { obj: ObjRef { fam: Dpni, num: 100 }, port: 0 }, b: EndpointRef { obj: ObjRef { fam: Dpni, num: 101 }, port: 0 } }
run 2 restool dprc connect dprc.1 --endpoint1=${OBJ_dpni_100} --endpoint2=${OBJ_dpni_101}
# expect: dpni_100 endpoint=dpni_101 link=down
probe 2 0 restool dpni info ${OBJ_dpni_100}

# ===== face: 2 cross-container populate->connect->bind =====

# step 3: CreateContainer { parent: ObjRef { fam: Dprc, num: 1 } }
OBJ_dprc_202="$(run_create 3 restool --script dprc create dprc.1)"
echo "dprc_202 ${OBJ_dprc_202}" >> "$RESULTS/created.txt"
# expect: dprc_202 present=true plugged=false
probe 3 0 restool dprc show dprc.1

# step 4: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_200="$(run_create 4 restool --script dpni create --container=dprc.1)"
echo "dpni_200 ${OBJ_dpni_200}" >> "$RESULTS/created.txt"
# expect: dpni_200 present=true plugged=false
probe 4 0 restool dprc show dprc.1

# step 5: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 202 } }
OBJ_dpni_201="$(run_create 5 restool --script dpni create --container=${OBJ_dprc_202})"
echo "dpni_201 ${OBJ_dpni_201}" >> "$RESULTS/created.txt"
# expect: dpni_201 present=true plugged=false
probe 5 0 restool dprc show ${OBJ_dprc_202}

# step 6: ConnectEdge { a: EndpointRef { obj: ObjRef { fam: Dpni, num: 200 }, port: 0 }, b: EndpointRef { obj: ObjRef { fam: Dpni, num: 201 }, port: 0 } }
run 6 restool dprc connect dprc.1 --endpoint1=${OBJ_dpni_200} --endpoint2=${OBJ_dpni_201}
# expect: dpni_200 endpoint=dpni_201 link=down
probe 6 0 restool dpni info ${OBJ_dpni_200}

# step 7: Plug { obj: ObjRef { fam: Dpni, num: 200 } }
run 7 restool dprc assign dprc.1 --object=${OBJ_dpni_200} --plugged=1
# expect: dpni_200 present=true plugged=true
probe 7 0 restool dprc show dprc.1

# step 8: Rescan { container: ObjRef { fam: Dprc, num: 1 } }
run 8 restool dprc sync

# step 9: DisconnectEdge { e: EndpointRef { obj: ObjRef { fam: Dpni, num: 200 }, port: 0 } }
run 9 restool dprc disconnect dprc.1 --endpoint=${OBJ_dpni_200}
# expect: dpni_200 endpoint=none
probe 9 0 restool dpni info ${OBJ_dpni_200}

# step 10: ConnectEdge { a: EndpointRef { obj: ObjRef { fam: Dpni, num: 200 }, port: 0 }, b: EndpointRef { obj: ObjRef { fam: Dpni, num: 201 }, port: 0 } }
run 10 restool dprc connect dprc.1 --endpoint1=${OBJ_dpni_200} --endpoint2=${OBJ_dpni_201}
# expect: dpni_200 endpoint=dpni_201 link=down
probe 10 0 restool dpni info ${OBJ_dpni_200}

# step 11: Unplug { obj: ObjRef { fam: Dpni, num: 200 } }
run 11 restool dprc assign dprc.1 --object=${OBJ_dpni_200} --plugged=0
# expect: dpni_200 present=true plugged=false driver_bound=false
probe 11 0 restool dprc show dprc.1
probe_link 11 1 /sys/bus/fsl-mc/devices/${OBJ_dpni_200}/driver

# ===== face: 3 child<->child generality =====

# step 12: CreateContainer { parent: ObjRef { fam: Dprc, num: 1 } }
OBJ_dprc_302="$(run_create 12 restool --script dprc create dprc.1)"
echo "dprc_302 ${OBJ_dprc_302}" >> "$RESULTS/created.txt"
# expect: dprc_302 present=true plugged=false
probe 12 0 restool dprc show dprc.1

# step 13: CreateContainer { parent: ObjRef { fam: Dprc, num: 1 } }
OBJ_dprc_303="$(run_create 13 restool --script dprc create dprc.1)"
echo "dprc_303 ${OBJ_dprc_303}" >> "$RESULTS/created.txt"
# expect: dprc_303 present=true plugged=false
probe 13 0 restool dprc show dprc.1

# step 14: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 302 } }
OBJ_dpni_300="$(run_create 14 restool --script dpni create --container=${OBJ_dprc_302})"
echo "dpni_300 ${OBJ_dpni_300}" >> "$RESULTS/created.txt"
# expect: dpni_300 present=true plugged=false
probe 14 0 restool dprc show ${OBJ_dprc_302}

# step 15: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 303 } }
OBJ_dpni_301="$(run_create 15 restool --script dpni create --container=${OBJ_dprc_303})"
echo "dpni_301 ${OBJ_dpni_301}" >> "$RESULTS/created.txt"
# expect: dpni_301 present=true plugged=false
probe 15 0 restool dprc show ${OBJ_dprc_303}

# step 16: ConnectEdge { a: EndpointRef { obj: ObjRef { fam: Dpni, num: 300 }, port: 0 }, b: EndpointRef { obj: ObjRef { fam: Dpni, num: 301 }, port: 0 } }
run 16 restool dprc connect dprc.1 --endpoint1=${OBJ_dpni_300} --endpoint2=${OBJ_dpni_301}
# expect: dpni_300 endpoint=dpni_301 link=down
probe 16 0 restool dpni info ${OBJ_dpni_300}

# ===== face: 4 create-side heal (consented rebind) =====

# step 17: CreateObject { fam: Dpmcp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpmcp_400="$(run_create 17 restool --script dpmcp create --container=dprc.1)"
echo "dpmcp_400 ${OBJ_dpmcp_400}" >> "$RESULTS/created.txt"
# expect: dpmcp_400 present=true plugged=false
probe 17 0 restool dprc show dprc.1

# step 18: CreateObject { fam: Dpbp, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpbp_400="$(run_create 18 restool --script dpbp create --container=dprc.1)"
echo "dpbp_400 ${OBJ_dpbp_400}" >> "$RESULTS/created.txt"
# expect: dpbp_400 present=true plugged=false
probe 18 0 restool dprc show dprc.1

# step 19: CreateObject { fam: Dpcon, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpcon_400="$(run_create 19 restool --script dpcon create --num-priorities=2 --container=dprc.1)"
echo "dpcon_400 ${OBJ_dpcon_400}" >> "$RESULTS/created.txt"
# expect: dpcon_400 present=true plugged=false
probe 19 0 restool dprc show dprc.1

# step 20: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_400="$(run_create 20 restool --script dpni create --container=dprc.1)"
echo "dpni_400 ${OBJ_dpni_400}" >> "$RESULTS/created.txt"
# expect: dpni_400 present=true plugged=false
probe 20 0 restool dprc show dprc.1

# step 21: Plug { obj: ObjRef { fam: Dpmcp, num: 400 } }
run 21 restool dprc assign dprc.1 --object=${OBJ_dpmcp_400} --plugged=1
# expect: dpmcp_400 present=true plugged=true
probe 21 0 restool dprc show dprc.1

# step 22: Plug { obj: ObjRef { fam: Dpbp, num: 400 } }
run 22 restool dprc assign dprc.1 --object=${OBJ_dpbp_400} --plugged=1
# expect: dpbp_400 present=true plugged=true
probe 22 0 restool dprc show dprc.1

# step 23: Plug { obj: ObjRef { fam: Dpcon, num: 400 } }
run 23 restool dprc assign dprc.1 --object=${OBJ_dpcon_400} --plugged=1
# expect: dpcon_400 present=true plugged=true
probe 23 0 restool dprc show dprc.1

# step 24: Plug { obj: ObjRef { fam: Dpni, num: 400 } }
run 24 restool dprc assign dprc.1 --object=${OBJ_dpni_400} --plugged=1
# expect: dpni_400 present=true plugged=true
probe 24 0 restool dprc show dprc.1

# step 25: Rescan { container: ObjRef { fam: Dprc, num: 1 } }
run 25 restool dprc sync

# step 26: KernelBind { obj: ObjRef { fam: Dpni, num: 400 } }
# awaited: the kernel probes plugged bus-visible objects on its own; observe the driver link
bind_settle /sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver ${OBJ_dpni_400}
# expect: dpni_400 driver_bound=true
probe_link 26 0 /sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver

# step 27: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_401="$(run_create 27 restool --script dpni create --container=dprc.1)"
echo "dpni_401 ${OBJ_dpni_401}" >> "$RESULTS/created.txt"
# expect: dpni_401 present=true plugged=false
probe 27 0 restool dprc show dprc.1

# step 28: Unbind { obj: ObjRef { fam: Dpni, num: 400 } }
sysfs_write 28 /sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver/unbind ${OBJ_dpni_400}
# expect: dpni_400 driver_bound=false
probe_link 28 0 /sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver

# step 29: KernelBind { obj: ObjRef { fam: Dpni, num: 400 } }
# awaited: the kernel probes plugged bus-visible objects on its own; observe the driver link
bind_settle /sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver ${OBJ_dpni_400}
# expect: dpni_400 driver_bound=true
# record (operator-diffed, not judged): a post-bind connect on this kernel-bound end logs ENDPOINT_CHANGED then -EPERM (discarded) — the dmesg law recorded here, the face with an explicit kernel-bound end (cross-dprc-links design D4); face 2 carries no kernelBind and is judged by dprc_get_connection from root
probe_link 29 0 /sys/bus/fsl-mc/devices/${OBJ_dpni_400}/driver

# step 30: Rescan { container: ObjRef { fam: Dprc, num: 1 } }
run 30 restool dprc sync

# ===== face: 5 destroy-mirror =====

# step 31: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_500="$(run_create 31 restool --script dpni create --container=dprc.1)"
echo "dpni_500 ${OBJ_dpni_500}" >> "$RESULTS/created.txt"
# expect: dpni_500 present=true plugged=false
probe 31 0 restool dprc show dprc.1

# step 32: Plug { obj: ObjRef { fam: Dpni, num: 500 } }
run 32 restool dprc assign dprc.1 --object=${OBJ_dpni_500} --plugged=1
# expect: dpni_500 present=true plugged=true
probe 32 0 restool dprc show dprc.1

# step 33: Rescan { container: ObjRef { fam: Dprc, num: 1 } }
run 33 restool dprc sync

# step 34: Destroy { obj: ObjRef { fam: Dpni, num: 500 } }
run 34 restool dpni destroy ${OBJ_dpni_500}
# expect: dpni_500 present=false
probe 34 0 restool dprc show dprc.1

# ===== face: 6 teardown laws (positive half) =====

# step 35: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_600="$(run_create 35 restool --script dpni create --container=dprc.1)"
echo "dpni_600 ${OBJ_dpni_600}" >> "$RESULTS/created.txt"
# expect: dpni_600 present=true plugged=false
probe 35 0 restool dprc show dprc.1

# step 36: CreateObject { fam: Dpni, container: ObjRef { fam: Dprc, num: 1 } }
OBJ_dpni_601="$(run_create 36 restool --script dpni create --container=dprc.1)"
echo "dpni_601 ${OBJ_dpni_601}" >> "$RESULTS/created.txt"
# expect: dpni_601 present=true plugged=false
probe 36 0 restool dprc show dprc.1

# step 37: ConnectEdge { a: EndpointRef { obj: ObjRef { fam: Dpni, num: 600 }, port: 0 }, b: EndpointRef { obj: ObjRef { fam: Dpni, num: 601 }, port: 0 } }
run 37 restool dprc connect dprc.1 --endpoint1=${OBJ_dpni_600} --endpoint2=${OBJ_dpni_601}
# expect: dpni_600 endpoint=dpni_601 link=down
probe 37 0 restool dpni info ${OBJ_dpni_600}

# step 38: DisconnectEdge { e: EndpointRef { obj: ObjRef { fam: Dpni, num: 600 }, port: 0 } }
run 38 restool dprc disconnect dprc.1 --endpoint=${OBJ_dpni_600}
# expect: dpni_600 endpoint=none
probe 38 0 restool dpni info ${OBJ_dpni_600}

# ----- banked witnesses (cited, not run) -----
# reference 39: child-issued connect refused No privilege (0x4) — models/board/V-DPCI-1 sitting: a dprc connect issued from a child container lacking TOPOLOGY_CHANGES_ALLOWED returns MC status 0x4 (No privilege); this suite connects at the root ancestor instead (cross-dprc-links design D2), so the refusal is cited, not re-run (cross-dprc-links design D10)

# --- suite hook: models/board/V-TRAF-1/vtraf1.hook.sh ---
# Hand-written steps that need the created objects standing; sourced so
# they see this script's variables and run under the teardown trap.
if grep -nE 'dpmac[.]3([^0-9]|$)|dpmac[.]17([^0-9]|$)|dpni[.]0([^0-9]|$)' "models/board/V-TRAF-1/vtraf1.hook.sh" | grep -v safety-self-check; then
  echo "refusing: total-deny object referenced in the hook" >&2  # safety-self-check
  exit 1
fi
. "models/board/V-TRAF-1/vtraf1.hook.sh"

echo "suite V-TRAF-1 complete"
